using System.ComponentModel.DataAnnotations;

namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class DengueRaterRNE
    {
        public string? jobid { get; set; }
        public string? batchid { get; set; }
        public string? splitid { get; set; }
        public TimeSpan? extractedon { get; set; }
        public short? qcstatus { get; set; }
        public string? qcmsdg { get; set; }
        public TimeSpan? qcon { get; set; }
        public short? ispreintreq { get; set; }
        public short? printstatus { get; set; }
        public string? printmesg { get; set; }
        public TimeSpan? printedon { get; set; }
        public string? partnerflag { get; set; }
        public TimeSpan? noticedate { get; set; }
        public decimal? qc_tot_premium { get; set; }
        public decimal? qc_service_tax { get; set; }
        public string? partnername { get; set; }
        public string? partneruniqueid { get; set; }
        public decimal? partnertotpremium { get; set; }
        public decimal? partner_tax { get; set; }
        public int prod_code { get; set; }
        public string? prod_name { get; set; }
        public string? split_flag { get; set; }
        public long? reference_num { get; set; }
        public TimeSpan? reference_date { get; set; }
        [Key]
        public string policy_number { get; set; }
        public long? branchcode { get; set; }
        public string? branchname { get; set; }
        public string? customer_id { get; set; }
        public string? customername { get; set; }
        public string? txt_salutation { get; set; }
        public string? location_code { get; set; }
        public string? txt_address_line_1 { get; set; }
        public string? txt_address_line_2 { get; set; }
        public string? txt_apartment { get; set; }
        public string? txt_street { get; set; }
        public string? txt_areavillage { get; set; }
        public string? txt_citydistrict { get; set; }
        public string? txt_state { get; set; }
        public string? state_code { get; set; }
        public string? state_regis { get; set; }
        public string? txt_pincode { get; set; }
        public string? txt_nationality { get; set; }
        public string? txt_mobile { get; set; }
        public string? txt_telephone { get; set; }
        public string? txt_dealer_cd { get; set; }
        public string? imdname { get; set; }
        public string? imdmobile { get; set; }
        public string? vertical_name { get; set; }
        public string? verticalname { get; set; }
        public DateTime? policy_start_date { get; set; }
        public DateTime? policy_expiry_date { get; set; }
        public string? policy_period { get; set; }
        public string? policyplan { get; set; }
        public string? policy_type { get; set; }
        public string? txt_family { get; set; }
        public string? tier_type { get; set; }
        public int? claimcount { get; set; }
        public decimal? num_tot_premium { get; set; }
        public decimal? num_net_premium { get; set; }
        public decimal? num_service_tax { get; set; }
        public string? txt_insuredname1 { get; set; }
        public string? txt_insuredname2 { get; set; }
        public string? txt_insuredname3 { get; set; }
        public string? txt_insuredname4 { get; set; }
        public string? txt_insuredname5 { get; set; }
        public string? txt_insuredname6 { get; set; }
        public string? txt_insured_dob1 { get; set; }
        public string? txt_insured_dob2 { get; set; }
        public string? txt_insured_dob3 { get; set; }
        public string? txt_insured_dob4 { get; set; }
        public string? txt_insured_dob5 { get; set; }
        public string? txt_insured_dob6 { get; set; }
        public string? txt_insured_relation1 { get; set; }
        public string? txt_insured_relation2 { get; set; }
        public string? txt_insured_relation3 { get; set; }
        public string? txt_insured_relation4 { get; set; }
        public string? txt_insured_relation5 { get; set; }
        public string? txt_insured_relation6 { get; set; }
        public string? txt_insured_age1 { get; set; }
        public string? txt_insured_age2 { get; set; }
        public string? txt_insured_age3 { get; set; }
        public string? txt_insured_age4 { get; set; }
        public string? txt_insured_age5 { get; set; }
        public string? txt_insured_age6 { get; set; }
        public string? txt_insured_gender1 { get; set; }
        public string? txt_insured_gender2 { get; set; }
        public string? txt_insured_gender3 { get; set; }
        public string? txt_insured_gender4 { get; set; }
        public string? txt_insured_gender5 { get; set; }
        public string? txt_insured_gender6 { get; set; }
        public string? txt_insured_relation7 { get; set; }
        public string? txt_insured_relation8 { get; set; }
        public string? txt_insured_relation9 { get; set; }
        public string? txt_insured_relation10 { get; set; }
        public string? txt_insured_relation11 { get; set; }
        public string? txt_insured_relation12 { get; set; }
        public string? member_id1 { get; set; }
        public string? member_id2 { get; set; }
        public string? member_id3 { get; set; }
        public string? member_id4 { get; set; }
        public string? member_id5 { get; set; }
        public string? member_id6 { get; set; }
        public string? nominee_name1 { get; set; }
        public string? nominee_name2 { get; set; }

        public string? nominee_name3 { get; set; }
        public string? nominee_name4 { get; set; }
        public string? nominee_name5 { get; set; }
        public string? nominee_name6 { get; set; }
        public string? nominee_relationship1 { get; set; }
        public string? nominee_relationship2 { get; set; }
        public string? nominee_relationship3 { get; set; }
        public string? nominee_relationship4 { get; set; }
        public string? nominee_relationship5 { get; set; }
        public string? nominee_relationship6 { get; set; }
        public string? pre_existing_disease1 { get; set; }
        public string? pre_existing_disease2 { get; set; }
        public string? pre_existing_disease3 { get; set; }
        public string? pre_existing_disease4 { get; set; }
        public string? pre_existing_disease5 { get; set; }
        public string? pre_existing_disease6 { get; set; }
        public decimal? sum_insured1 { get; set; }
        public decimal? sum_insured2 { get; set; }
        public decimal? sum_insured3 { get; set; }
        public decimal? sum_insured4 { get; set; }
        public decimal? sum_insured5 { get; set; }
        public decimal? sum_insured6 { get; set; }
        public decimal? insured_cb1 { get; set; }
        public decimal? insured_cb2 { get; set; }
        public decimal? insured_cb3 { get; set; }
        public decimal? insured_cb4 { get; set; }
        public decimal? insured_cb5 { get; set; }
        public decimal? insured_cb6 { get; set; }
        public decimal? premium_insured1 { get; set; }
        public decimal? premium_insured2 { get; set; }
        public decimal? premium_insured3 { get; set; }
        public decimal? premium_insured4 { get; set; }
        public decimal? premium_insured5 { get; set; }
        public decimal? premium_insured6 { get; set; }
        public decimal? insured_deductable1 { get; set; }
        public decimal? insured_deductable2 { get; set; }
        public decimal? insured_deductable3 { get; set; }
        public decimal? insured_deductable4 { get; set; }
        public decimal? insured_deductable5 { get; set; }
        public decimal? insured_deductable6 { get; set; }
        public decimal? insured_loadingper1 { get; set; }
        public decimal? insured_loadingper2 { get; set; }
        public decimal? insured_loadingper3 { get; set; }
        public decimal? insured_loadingper4 { get; set; }
        public decimal? insured_loadingper5 { get; set; }
        public decimal? insured_loadingper6 { get; set; }
        public decimal? insured_loadingamt1 { get; set; }
        public decimal? insured_loadingamt2 { get; set; }
        public decimal? insured_loadingamt3 { get; set; }
        public decimal? insured_loadingamt4 { get; set; }
        public decimal? insured_loadingamt5 { get; set; }
        public decimal? insured_loadingamt6 { get; set; }
        public decimal? insured_loadingper7 { get; set; }
        public decimal? insured_loadingper8 { get; set; }
        public decimal? insured_loadingper9 { get; set; }
        public decimal? insured_loadingper10 { get; set; }
        public decimal? insured_loadingper11 { get; set; }
        public decimal? insured_loadingper12 { get; set; }
        public decimal? insured_loadingamt7 { get; set; }
        public decimal? insured_loadingamt8 { get; set; }
        public decimal? insured_loadingamt9 { get; set; }
        public decimal? insured_loadingamt10 { get; set; }
        public decimal? insured_loadingamt11 { get; set; }
        public decimal? insured_loadingamt12 { get; set; }
        public decimal? insured_rb_claimamt1 { get; set; }
        public decimal? insured_rb_claimamt2 { get; set; }
        public decimal? insured_rb_claimamt3 { get; set; }
        public decimal? insured_rb_claimamt4 { get; set; }
        public decimal? insured_rb_claimamt5 { get; set; }
        public decimal? insured_rb_claimamt6 { get; set; }
        public decimal? copayper1 { get; set; }
        public decimal? copayper2 { get; set; }
        public decimal? copayper3 { get; set; }
        public decimal? copayper4 { get; set; }
        public decimal? copayper5 { get; set; }
        public decimal? copayper6 { get; set; }
        public decimal? copayamt1 { get; set; }
        public decimal? copayamt2 { get; set; }
        public decimal? copayamt3 { get; set; }
        public decimal? copayamt4 { get; set; }
        public decimal? copayamt5 { get; set; }
        public decimal? copayamt6 { get; set; }
        public decimal? fitness_discount1 { get; set; }
        public decimal? fitness_discount2 { get; set; }
        public decimal? fitness_discount3 { get; set; }
        public decimal? fitness_discount4 { get; set; }
        public decimal? fitness_discount5 { get; set; }
        public decimal? fitness_discount6 { get; set; }
        public decimal? health_incentive1 { get; set; }
        public decimal? health_incentive2 { get; set; }
        public decimal? health_incentive3 { get; set; }
        public decimal? health_incentive4 { get; set; }
        public decimal? health_incentive5 { get; set; }
        public decimal? health_incentive6 { get; set; }
        public decimal? wellness_discount1 { get; set; }
        public decimal? wellness_discount2 { get; set; }
        public decimal? wellness_discount3 { get; set; }
        public decimal? wellness_discount4 { get; set; }
        public decimal? wellness_discount5 { get; set; }
        public decimal? wellness_discount6 { get; set; }
        public decimal? stayactive1 { get; set; }
        public decimal? stayactive2 { get; set; }
        public decimal? stayactive3 { get; set; }
        public decimal? stayactive4 { get; set; }
        public decimal? stayactive5 { get; set; }
        public decimal? stayactive6 { get; set; }
    }
}
