namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class EasyHealthGC
    {
        public long policy_no { get; set; }
        public long batch_id { get; set; }
        public long customer_id { get; set; }
        public string customer_name { get; set; }
        public string salutation { get; set; }
        public string location_code { get; set; }
        public string apartment { get; set; }
        public string street { get; set; }
        public string area { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string state_code { get; set; }
        public string region { get; set; }
        public long pincode { get; set; }
        public string nationality { get; set; }
        public long mobile { get; set; }
        public long telephone { get; set; }
        public string email { get; set; }
        public decimal? intermediary_code { get; set; }
        public string intermediary_name { get; set; }
        public string psm_code { get; set; }    
        public string psm_name { get; set; }
        public string insured_name_1 { get; set;}
        public string insured_name_2 { get; set;}
        public string insured_name_3 { get; set;}
        public string insured_name_4 { get; set;}
        public string insured_name_5 { get; set;}
        public string insured_name_6 { get; set;}
        public decimal? insured_memberid_1 { get; set; }
        public decimal? insured_memberid_2 { get; set; }
        public decimal? insured_memberid_3 { get; set; }
        public decimal? insured_memberid_4 { get; set; }
        public decimal? insured_memberid_5 { get; set; }
        public decimal? insured_memberid_6 { get; set; }
        public decimal? loading_per_insured_1 { get; set; }
        public decimal? loading_per_insured_2 { get; set; }
        public decimal? loading_per_insured_3 { get; set; }
        public decimal? loading_per_insured_4 { get; set; }
        public decimal? loading_per_insured_5 { get; set; }
        public decimal? loading_per_insured_6 { get; set; }
        public decimal? loading_amount_insured_1 { get; set; }
        public decimal? loading_amount_insured_2 { get; set; }
        public decimal? loading_amount_insured_3 { get; set; }
        public decimal? loading_amount_insured_4 { get; set; }
        public decimal? loading_amount_insured_5 { get; set; }
        public decimal? loading_amount_insured_6 { get; set; }
        public DateTime? insured_dob_1 { get; set; }
        public DateTime? insured_dob_2 { get; set; }
        public DateTime? insured_dob_3 { get; set; }
        public DateTime? insured_dob_4 { get; set; }
        public DateTime? insured_dob_5 { get; set; }
        public DateTime? insured_dob_6 { get; set; }
        public int? insured_age_1 { get; set; }
        public int? insured_age_2 { get; set; }
        public int? insured_age_3 { get; set; }
        public int? insured_age_4 { get; set; }
        public int? insured_age_5 { get; set; }
        public int? insured_age_6 { get; set; }
        public int? insured_gender_1 { get; set; }
        public int? insured_gender_2 { get; set; }
        public int? insured_gender_3 { get; set; }
        public int? insured_gender_4 { get; set; }
        public int? insured_gender_5 { get; set; }
        public int? insured_gender_6 { get; set; }
        public string? insured_relation_1 { get; set; }
        public string? insured_relation_2 { get; set; }
        public string? insured_relation_3 { get; set; }
        public string? insured_relation_4 { get; set; }
        public string? insured_relation_5 { get; set; }
        public string? insured_relation_6 { get; set; }
        public bool ped_1 { get; set; }
        public bool ped_2 { get; set; }
        public bool ped_3 { get; set; }
        public bool ped_4 { get; set; }
        public bool ped_5 { get; set; }
        public bool ped_6 { get; set; }
        public decimal? deductables_insured_1 { get; set; }
        public decimal? deductables_insured_2 { get; set; }
        public decimal? deductables_insured_3 { get; set; }
        public decimal? deductables_insured_4 { get; set; }
        public decimal? deductables_insured_5 { get; set; }
        public decimal? deductables_insured_6 { get; set; }
        public long wellness_1 { get; set; }
        public long wellness_2 { get; set; }
        public long wellness_3 { get; set; }
        public long wellness_4 { get; set; }
        public long wellness_5 { get; set; }
        public long wellness_6 { get; set; }
        public long stay_activ_1 { get; set; }
        public long stay_activ_2 { get; set; }
        public long stay_activ_3 { get; set; }
        public long stay_activ_4 { get; set; }
        public long stay_activ_5 { get; set; }
        public long stay_activ_6 { get; set; }
        public decimal? basic_loading_rate_1 { get; set; }
        public decimal? basic_loading_rate_2 { get; set; }
        public decimal? basic_loading_rate_3 { get; set; }
        public decimal? basic_loading_rate_4 { get; set; }
        public decimal? basic_loading_rate_5 { get; set; }
        public decimal? basic_loading_rate_6 { get; set; }
        public decimal? fitness_discount_1 { get; set; }
        public decimal? fitness_discount_2 { get; set; }
        public decimal? fitness_discount_3 { get; set; }
        public decimal? fitness_discount_4 { get; set; }
        public decimal? fitness_discount_5 { get; set; }
        public decimal? fitness_discount_6 { get; set; }
        public decimal? health_incentive_1 { get; set; }
        public decimal? health_incentive_2 { get; set; }
        public decimal? health_incentive_3 { get; set; }
        public decimal? health_incentive_4 { get; set; }
        public decimal? health_incentive_5 { get; set; }
        public decimal? health_incentive_6 { get; set; }
        public decimal? reserv_benefit_1 { get; set; }
        public decimal? reserv_benefit_2 { get; set; }
        public decimal? reserv_benefit_3 { get; set; }
        public decimal? reserv_benefit_4 { get; set; }
        public decimal? reserv_benefit_5 { get; set; }
        public decimal? reserv_benefit_6 { get; set; }
        public decimal? rb_claimed_amt_1 { get; set; }
        public decimal? rb_claimed_amt_2 { get; set; }
        public decimal? rb_claimed_amt_3 { get; set; }
        public decimal? rb_claimed_amt_4 { get; set; }
        public decimal? rb_claimed_amt_5 { get; set; }
        public decimal? rb_claimed_amt_6 { get; set; }
        public string? policy_ld_desc_1 { get; set; }
        public string? policy_ld_desc_2 { get; set; }
        public string? policy_ld_desc_3 { get; set; }
        public string? policy_ld_desc_4 { get; set; }
        public string? policy_ld_desc_5 { get; set; }
        public decimal? policy_ld_amount_1 { get; set; }
        public decimal? policy_ld_amount_2 { get; set; }
        public decimal? policy_ld_amount_3 { get; set; }
        public decimal? policy_ld_amount_4 { get; set; }
        public decimal? policy_ld_amount_5 { get; set; }
        public decimal? policy_ld_rate_1 { get; set; }
        public decimal? policy_ld_rate_2 { get; set; }
        public decimal? policy_ld_rate_3 { get; set; }
        public decimal? policy_ld_rate_4 { get; set; }
        public decimal? policy_ld_rate_5 { get; set; }
        public string preventive_hc { get; set; }
        public long job_id { get; set; }
        public DateTime? notice_date { get; set; }
        public long product_cd { get; set; }
        public string product_name { get; set; }
        public long proposal_no { get; set; }
        public long policy_no_16 { get; set; }
        public long hehi_policy_no { get; set; }
        public long banch_code { get; set; }
        public string branch_name { get; set; }
        public string split_flag { get; set; }
        public DateTime? policy_start_date { get; set; }
        public DateTime? policy_end_date { get; set; }
        public string policy_period { get; set; }
        public string tier { get; set; }
        public string policy_plan { get; set; }
        public string policy_type { get; set; }
        public string family_size { get; set; }
        public long claim_count { get; set; }
        public bool rn_flag { get; set; }
        public bool vip_flag { get; set; }
        public bool age_change_flag { get; set; }
        public bool tier_change_flag { get; set; }
        public bool loading_change_flag { get; set; }
        public string txt_remarks { get; set; }
        public long master_policy_no { get; set; }
        public long customer_uin { get; set; }
        public bool pre_policy_claim_flag { get; set; }
        public bool lifecycle_claim_flag { get; set; }
        public long num_tot_additional_child { get; set; }
        public string gc_reporting_code { get; set; }
        public string remarks { get; set; }
        public string data { get; set; }
        public long pb_1 { get; set; }
        public long pb_2 { get; set; }
        public long pb_3 { get; set; }
        public long pb_4 { get; set; }
        public long pb_5 { get; set; }
        public long pb_6 { get; set; }
        public bool exclusion_1 { get; set; }
        public bool exclusion_2 { get; set; }
        public bool exclusion_3 { get; set; }
        public bool exclusion_4 { get; set; }
        public bool exclusion_5 { get; set; }
        public bool exclusion_6 { get; set; }
        public decimal? si_1 { get; set; }
        public decimal? si_2 { get; set; }
        public decimal? si_3 { get; set; }
        public decimal? si_4 { get; set; }
        public decimal? si_5 { get; set; }
        public decimal? si_6 { get; set; }
        public long? cb_1 { get; set; }
        public long? cb_2 { get; set; }
        public long? cb_3 { get; set; }
        public long? cb_4 { get; set; }
        public long? cb_5 { get; set; }
        public long? cb_6 { get; set; }
        public long sb_1 { get; set; }
        public long sb_2 { get; set; }
        public long sb_3 { get; set; }
        public long sb_4 { get; set; }
        public long sb_5 { get; set; }
        public long sb_6 { get; set; }
        public DateTime? first_inception_date_1 { get; set; }
        public DateTime? first_inception_date_2 { get; set; }
        public DateTime? first_inception_date_3 { get; set; }
        public DateTime? first_inception_date_4 { get; set; }
        public DateTime? first_inception_date_5 { get; set; }
        public DateTime? first_inception_date_6 { get; set; }
        public decimal? co_pay_amt_1 { get; set; }
        public decimal? co_pay_amt_2 { get; set; }
        public decimal? co_pay_amt_3 { get; set; }
        public decimal? co_pay_amt_4 { get; set; }
        public decimal? co_pay_amt_5 { get; set; }
        public decimal? co_pay_amt_6 { get; set; }
        public decimal? co_pay_1 { get; set; }
        public decimal? co_pay_2 { get; set; }
        public decimal? co_pay_3 { get; set; }
        public decimal? co_pay_4 { get; set; }
        public decimal? co_pay_5 { get; set; }
        public decimal? co_pay_6 { get; set; }
        public decimal? upsell_type_1 { get; set; }
        public decimal? upsell_type_2 { get; set; }
        public decimal? upsell_type_3 { get; set; }
        public decimal? upsell_value_1 { get; set; }
        public decimal? upsell_value_2 { get; set; }
        public decimal? upsell_value_3 { get; set; }
        public decimal? tot_premium { get; set; }
        public decimal? net_premium { get; set; }
      
        public decimal? premium_insured_1 { get; set; }
        public decimal? premium_insured_2 { get; set; }
        public decimal? premium_insured_3 { get; set; }
        public decimal? premium_insured_4 { get; set; }
        public decimal? premium_insured_5 { get; set; }
        public decimal? premium_insured_6 { get; set; }
        public decimal? upsell_premium_1 { get; set; }
        public decimal? upsell_premium_2 { get; set; }
        public decimal? upsell_premium_3 { get; set; }
        public decimal? upsell_gst_1 { get; set; }
        public decimal? upsell_gst_2 { get; set; }
        public decimal? upsell_gst_3 { get; set; }
        public decimal? rider_si_11 { get; set; }
        public decimal? rider_prem_11 { get; set; }
        public decimal? rider_loading_rate_11 { get; set; }
        public decimal? rider_si_12 { get; set; }
        public decimal? rider_prem_12 { get; set; }
        public decimal? rider_loading_rate_12 { get; set; }
        public decimal? rider_si_13 { get; set; }
        public decimal? rider_prem_13 { get; set; }
        public decimal? rider_loading_rate_13 { get; set; }
        public decimal? rider_si_14 { get; set; }
        public decimal? rider_prem_14 { get; set; }
        public decimal? rider_loading_rate_14 { get; set; }
        public decimal? rider_si_15 { get; set; }
        public decimal? rider_prem_15 { get; set; }
        public decimal? rider_loading_rate_15 { get; set; }
        public decimal? rider_si_16 { get; set; }
        public decimal? rider_prem_16 { get; set; }
        public decimal? rider_loading_rate_16 { get; set; }
        public decimal? rider_si_17 { get; set; }
        public decimal? rider_prem_17 { get; set; }
        public decimal? rider_loading_rate_17 { get; set; }
        public decimal? rider_si_18 { get; set; }
        public decimal? rider_prem_18 { get; set; }
        public decimal? rider_loading_rate_18 { get; set; }
        public decimal? rider_si_19 { get; set; }
        public decimal? rider_prem_19 { get; set; }
        public decimal? rider_loading_rate_19 { get; set; }
        public decimal? rider_si_21 { get; set; }
        public decimal? rider_prem_21 { get; set; }
        public decimal? rider_loading_rate_21 { get; set; }
        public decimal? rider_si_22 { get; set; }
        public decimal? rider_prem_22 { get; set; }
        public decimal? rider_loading_rate_22 { get; set; }
        public decimal? rider_si_23 { get; set; }
        public decimal? rider_prem_23 { get; set; }
        public decimal? rider_loading_rate_23 { get; set; }
        public decimal? rider_si_24 { get; set; }
        public decimal? rider_prem_24 { get; set; }
        public decimal? rider_loading_rate_24 { get; set; }
        public decimal? rider_si_25 { get; set; }
        public decimal? rider_prem_25 { get; set; }
        public decimal? rider_loading_rate_25 { get; set; }
        public decimal? rider_si_26 { get; set; }
        public decimal? rider_prem_26 { get; set; }
        public decimal? rider_loading_rate_26 { get; set; }
        public decimal? rider_si_27 { get; set; }
        public decimal? rider_prem_27 { get; set; }
        public decimal? rider_loading_rate_27 { get; set; }
        public decimal? rider_si_28 { get; set; }
        public decimal? rider_prem_28 { get; set; }
        public decimal? rider_loading_rate_28 { get; set; }
        public decimal? rider_si_29 { get; set; }
        public decimal? rider_prem_29 { get; set; }
        public decimal? rider_loading_rate_29 { get; set; }
        public decimal? rider_si_31 { get; set; }
        public decimal? rider_prem_31 { get; set; }
        public decimal? rider_loading_rate_31 { get; set; }
        public decimal? rider_si_32 { get; set; }
        public decimal? rider_prem_32 { get; set; }
        public decimal? rider_loading_rate_32 { get; set; }
        public decimal? rider_si_33 { get; set; }
        public decimal? rider_prem_33 { get; set; }
        public decimal? rider_loading_rate_33 { get; set; }
        public decimal? rider_si_34 { get; set; }
        public decimal? rider_prem_34 { get; set; }
        public decimal? rider_loading_rate_34 { get; set; }
        public decimal? rider_si_35 { get; set; }
        public decimal? rider_prem_35 { get; set; }
        public decimal? rider_loading_rate_35 { get; set; }
        public decimal? rider_si_36 { get; set; }
        public decimal? rider_prem_36 { get; set; }
        public decimal? rider_loading_rate_36 { get; set; }
        public decimal? rider_si_37 { get; set; }
        public decimal? rider_prem_37 { get; set; }
        public decimal? rider_loading_rate_37 { get; set; }
        public decimal? rider_si_38 { get; set; }
        public decimal? rider_prem_38 { get; set; }
        public decimal? rider_loading_rate_38 { get; set; }
        public decimal? rider_si_39 { get; set; }
        public decimal? rider_prem_39 { get; set; }
        public decimal? rider_loading_rate_39 { get; set; }
        public decimal? rider_si_41 { get; set; }
        public decimal? rider_prem_41 { get; set; }
        public decimal? rider_loading_rate_41 { get; set; }
        public decimal? rider_si_42 { get; set; }
        public decimal? rider_prem_42 { get; set; }
        public decimal? rider_loading_rate_42 { get; set; }
        public decimal? rider_si_43 { get; set; }
        public decimal? rider_prem_43 { get; set; }
        public decimal? rider_loading_rate_43 { get; set; }
        public decimal? rider_si_44 { get; set; }
        public decimal? rider_prem_44 { get; set; }
        public decimal? rider_loading_rate_44 { get; set; }
        public decimal? rider_si_45 { get; set; }
        public decimal? rider_prem_45 { get; set; }
        public decimal? rider_loading_rate_45 { get; set; }
        public decimal? rider_si_46 { get; set; }
        public decimal? rider_prem_46 { get; set; }
        public decimal? rider_loading_rate_46 { get; set; }
        public decimal? rider_si_47 { get; set; }
        public decimal? rider_prem_47 { get; set; }
        public decimal? rider_loading_rate_47 { get; set; }
        public decimal? rider_si_48 { get; set; }
        public decimal? rider_prem_48 { get; set; }
        public decimal? rider_loading_rate_48 { get; set; }
        public decimal? rider_si_49 { get; set; }
        public decimal? rider_prem_49 { get; set; }
        public decimal? rider_loading_rate_49 { get; set; }
        public decimal? rider_si_51 { get; set; }
        public decimal? rider_prem_51 { get; set; }
        public decimal? rider_loading_rate_51 { get; set; }
        public decimal? rider_si_52 { get; set; }
        public decimal? rider_prem_52 { get; set; }
        public decimal? rider_loading_rate_52 { get; set; }
        public decimal? rider_si_53 { get; set; }
        public decimal? rider_prem_53 { get; set; }
        public decimal? rider_loading_rate_53 { get; set; }
        public decimal? rider_si_54 { get; set; }
        public decimal? rider_prem_54 { get; set; }
        public decimal? rider_loading_rate_54 { get; set; }
        public decimal? rider_si_55 { get; set; }
        public decimal? rider_prem_55 { get; set; }
        public decimal? rider_loading_rate_55 { get; set; }
        public decimal? rider_si_56 { get; set; }
        public decimal? rider_prem_56 { get; set; }
        public decimal? rider_loading_rate_56 { get; set; }
        public decimal? rider_si_57 { get; set; }
        public decimal? rider_prem_57 { get; set; }
        public decimal? rider_loading_rate_57 { get; set; }
        public decimal? rider_si_58 { get; set; }
        public decimal? rider_prem_58 { get; set; }
        public decimal? rider_loading_rate_58 { get; set; }
        public decimal? rider_si_59 { get; set; }
        public decimal? rider_prem_59 { get; set; }
        public decimal? rider_loading_rate_59 { get; set; }
        public decimal? rider_si_61 { get; set; }
        public decimal? rider_prem_61 { get; set; }
        public decimal? rider_loading_rate_61 { get; set; }
        public decimal? rider_si_62 { get; set; }
        public decimal? rider_prem_62 { get; set; }
        public decimal? rider_loading_rate_62 { get; set; }
        public decimal? rider_si_63 { get; set; }
        public decimal? rider_prem_63 { get; set; }
        public decimal? rider_loading_rate_63 { get; set; }
        public decimal? rider_si_64 { get; set; }
        public decimal? rider_prem_64 { get; set; }
        public decimal? rider_loading_rate_64 { get; set; }
        public decimal? rider_si_65 { get; set; }
        public decimal? rider_prem_65 { get; set; }
        public decimal? rider_loading_rate_65 { get; set; }
        public decimal? rider_si_66 { get; set; }
        public decimal? rider_prem_66 { get; set; }
        public decimal? rider_loading_rate_66 { get; set; }
        public string? rider_name_11 { get; set; }
        public string? rider_name_12 { get; set; }
        public string? rider_name_13 { get; set; }
        public string? rider_name_14 { get; set; }
        public string? rider_name_15 { get; set; }

        public string? rider_name_16 { get; set; }
        public string? rider_name_17 { get; set; }
        public string? rider_name_18 { get; set; }
        public string? rider_name_19 { get; set; }
        public string? rider_name_21 { get; set; }
        public string? rider_name_22 { get; set; }
        public string? rider_name_23 { get; set; }
        public string? rider_name_24 { get; set; }
        public string? rider_name_25 { get; set; }
        public string? rider_name_26 { get; set; }
        public string? rider_name_27 { get; set; }
        public string? rider_name_28 { get; set; }
        public string? rider_name_29 { get; set; }
        public string? rider_name_31 { get; set; }
        public string? rider_name_32 { get; set; }
        public string? rider_name_33 { get; set; }
        public string? rider_name_34 { get; set; }
        public string? rider_name_35 { get; set; }
        public string? rider_name_36 { get; set; }
        public string? rider_name_37 { get; set; }
        public string? rider_name_38 { get; set; }
        public string? rider_name_39 { get; set; }
        public string? rider_name_41 { get; set; }
        public string? rider_name_42 { get; set; }
        public string? rider_name_43 { get; set; }
        public string? rider_name_44 { get; set; }
        public string? rider_name_45 { get; set; }
        public string? rider_name_46 { get; set; }
        public string? rider_name_47 { get; set; }
        public string? rider_name_48 { get; set; }
        public string? rider_name_49 { get; set; }
        public string? rider_name_51 { get; set; }
        public string? rider_name_52 { get; set; }
        public string? rider_name_53 { get; set; }
        public string? rider_name_54 { get; set; }
        public string? rider_name_55 { get; set; }
        public string? rider_name_56 { get; set; }
        public string? rider_name_57 { get; set; }
        public string? rider_name_58 { get; set; }
        public string? rider_name_59 { get; set; }
        public string? rider_name_61 { get; set; }
        public string? rider_name_62 { get; set; }
        public string? rider_name_63 { get; set; }
        public string? rider_name_64 { get; set; }
        public string? rider_name_65 { get; set; }
        public string? rider_name_66 { get; set; }
        public int? ca_si_1 { get; set; }
        public int? ca_si_2 { get; set; }
        public int? ca_si_3 { get; set; }
        public int? ca_si_4 { get; set; }
        public int? ca_si_5 { get; set; }
        public int? ca_si_6 { get; set; }
        public decimal? loyalty_discount { get; set; }
        public decimal? employee_discount { get; set; }
        public decimal? online_discount { get; set; }
        public decimal? family_discount { get; set; }
        public decimal? longterm_discount { get; set; }
        public decimal? family_discount_PRHDC { get; set; }
        public decimal? base_Premium1 { get; set; }
        public decimal? base_Premium2 { get; set; }
        public decimal? base_Premium3 { get; set; }
        public decimal? base_Premium4 { get; set; }
        public decimal? base_Premium5 { get; set; }
        public decimal? base_Premium6 { get; set; }
        public decimal? base_Premium { get; set; }
        public decimal? basePremLoading_Insured1 { get; set; }
        public decimal? basePremLoading_Insured2 { get; set; }
        public decimal? basePremLoading_Insured3 { get; set; }
        public decimal? basePremLoading_Insured4 { get; set; }
        public decimal? basePremLoading_Insured5 { get; set; }
        public decimal? basePremLoading_Insured6 { get; set; }
        public decimal? basePrem_Loading { get; set; }
        public decimal? easyHealth_BaseAndLoading_Premium { get; set; }
        public decimal? easyHealth_Loyalty_Discount { get; set; }
        public decimal? easyHealth_Employee_Discount { get; set; }
        public decimal? easyHealth_Online_Discount { get; set; }
        public decimal? easyHealth_Family_Discount { get; set; }
        public decimal? easyHealth_LongTerm_Discount { get; set; }
        public decimal? easyHealth_ORase_Premium { get; set; }
        public string? hdc_opt { get; set; }
        public decimal? hdc_si { get; set; }
        public decimal? hdc_rider_premium { get; set; }
        public decimal? hdc_family_discount { get; set; }
        public decimal? hdc_longterm_discount { get; set; }
        public decimal? hdc_final_premium { get; set; }
        public decimal? hdc_Rider_Premium1 { get; set; }
        public decimal? hdc_Rider_Premium2 { get; set; }
        public decimal? hdc_Rider_Premium3 { get; set; }
        public decimal? hdc_Rider_Premium4 { get; set; }
        public decimal? hdc_Rider_Premium5 { get; set; }
        public decimal? hdc_Rider_Premium6 { get; set; }
        public string? cI_rider_Opt { get; set; }
        public decimal? cI_si_1 { get; set; }
        public decimal? cI_si_2 { get; set; }
        public decimal? cI_si_3 { get; set; }
        public decimal? cI_si_4 { get; set; }
        public decimal? cI_si_5 { get; set; }
        public decimal? cI_si_6 { get; set; }
        public decimal? criticalIllness_Rider_Insured1 { get; set; }
        public decimal? criticalIllness_Rider_Insured2 { get; set; }
        public decimal? criticalIllness_Rider_Insured3 { get; set; }
        public decimal? criticalIllness_Rider_Insured4 { get; set; }
        public decimal? criticalIllness_Rider_Insured5 { get; set; }
        public decimal? criticalIllness_Rider_Insured6 { get; set; }
        public decimal? criticalIllness_Rider_BasePremium { get; set; }
        public decimal? criticalIllness_Rider_FamilyDiscount { get; set; }
        public decimal? criticalIllness_Rider_LongTermDiscount { get; set; }
        public decimal? criticalIllness_Rider_Premium { get; set; }
        public string? pr_opt { get; set; }
        public decimal? pr_insured_1 { get; set; }
        public decimal? pr_insured_2 { get; set; }
        public decimal? pr_insured_3 { get; set; }
        public decimal? pr_insured_4 { get; set; }
        public decimal? pr_insured_5 { get; set; }
        public decimal? pr_insured_6 { get; set; }
        public decimal? pr_ProtectorRider_Premium { get; set; }
        public decimal? pr_loading_insured1 { get; set; }
        public decimal? pr_loading_insured2 { get; set; }
        public decimal? pr_loading_insured3 { get; set; }
        public decimal? pr_loading_insured4 { get; set; }
        public decimal? pr_loading_insured5 { get; set; }
        public decimal? pr_loading_insured6 { get; set; }
        public decimal? pr_protectorriderloading_premium { get; set; }
        public decimal? pr_BaseLoading_Premium { get; set; }
        public decimal? pr_Family_Discount { get; set; }
        public decimal? pr_LongTerm_Discount { get; set; }
        public decimal? prpremium_Protector_Rider_Premium { get; set; }
        public string? individual_personalAR_opt { get; set; }
        public decimal? individual_personalAR_SI { get; set; }
        public decimal? individual_personalAR_Amt { get; set; }
        public decimal? individual_personalAR_LongTermDiscount { get; set; }
        public decimal? individual_Personal_AccidentRiderPremium { get; set; }
        public string? criticalAdvantage_Rider_opt { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_1 { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_2 { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_3 { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_4 { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_5 { get; set; }
        public decimal? criticalAdvantageRider_SumInsured_6 { get; set; }
        public decimal? criticalAdvantageRider_Insured_1 { get; set; }
        public decimal? criticalAdvantageRider_Insured_2 { get; set; }
        public decimal? criticalAdvantageRider_Insured_3 { get; set; }
        public decimal? criticalAdvantageRider_Insured_4 { get; set; }
        public decimal? criticalAdvantageRider_Insured_5 { get; set; }
        public decimal? criticalAdvantageRider_Insured_6 { get; set; }
        public decimal? criticalAdvantage_RiderBase_Premium { get; set; }

        public decimal? criticalAdvrider_loadinginsured1 { get; set; }
        public decimal? criticalAdvrider_loadinginsured2 { get; set; }
        public decimal? criticalAdvrider_loadinginsured3 { get; set; }
        public decimal? criticalAdvrider_loadinginsured4 { get; set; }
        public decimal? criticalAdvrider_loadinginsured5 { get; set; }
        public decimal? criticalAdvrider_loadinginsured6 { get; set; }
        public decimal? criticalAdvriderloading { get; set; }
        public decimal? criticalAdvriderbase_loading_premium { get; set; }
        public decimal? criticalAdvRiderPremium_Family_Discount { get; set; }
        public decimal? criticalAdvRiderPremium_LongTerm_Discount { get; set; }
        public decimal? criticalAdv_Rider_Premium { get; set; }
        public decimal? final_Premium { get; set; }
        public decimal? gst { get; set; }
        public decimal? cross_Check { get; set; }
        public decimal? easyhealth_total_Premium { get; set; }
        public decimal? easyhealth_netpremium { get; set; }
        public decimal? easy_health_gst { get; set; }

    }
}
