using System.ComponentModel.DataAnnotations;

namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class gc_rider_details
    {
        public long batch_id { get; set; }
        public int rider_si_11 { get; set; }
        public decimal rider_prem_11 { get; set; }
        public int rider_loading_rate_11 { get; set; }
        public int rider_si_12 { get; set; }
        public decimal rider_prem_12 { get; set; }
        public int rider_loading_rate_12 { get; set; }
        public int rider_si_13 { get; set; }
        public decimal rider_prem_13 { get; set; }
        public int rider_loading_rate_13 { get; set; }
        public int rider_si_14 { get; set; }
        public decimal rider_prem_14 { get; set; }
        public int rider_loading_rate_14 { get; set; }
        public int rider_si_15 { get; set; }
        public decimal rider_prem_15 { get; set; }
        public int rider_loading_rate_15 { get; set; }
        public int rider_si_16 { get; set; }
        public decimal rider_prem_16 { get; set; }
        public int rider_loading_rate_16 { get; set; }
        public int rider_si_17 { get; set; }
        public decimal rider_prem_17 { get; set; }
        public int rider_loading_rate_17 { get; set; }
        public int rider_si_18 { get; set; }
        public decimal rider_prem_18 { get; set; }
        public int rider_loading_rate_18 { get; set; }
        public int rider_si_19 { get; set; }
        public decimal rider_prem_19 { get; set; }
        public int rider_loading_rate_19 { get; set; }
        public int rider_si_21 { get; set; }
        public decimal rider_prem_21 { get; set; }
        public int rider_loading_rate_21 { get; set; }
        public int rider_si_22 { get; set; }
        public decimal rider_prem_22 { get; set; }
        public int rider_loading_rate_22 { get; set; }
        public int rider_si_23 { get; set; }
        public decimal rider_prem_23 { get; set; }
        public int rider_loading_rate_23 { get; set; }
        public int rider_si_24 { get; set; }
        public decimal rider_prem_24 { get; set; }
        public int rider_loading_rate_24 { get; set; }
        public int rider_si_25 { get; set; }
        public decimal rider_prem_25 { get; set; }
        public int rider_loading_rate_25 { get; set; }
        public int rider_si_26 { get; set; }
        public decimal rider_prem_26 { get; set; }
        public int rider_loading_rate_26 { get; set; }
        public int rider_si_27 { get; set; }
        public decimal rider_prem_27 { get; set; }
        public int rider_loading_rate_27 { get; set; }
        public int rider_si_28 { get; set; }
        public decimal rider_prem_28 { get; set; }
        public int rider_loading_rate_28 { get; set; }
        public int rider_si_29 { get; set; }
        public decimal rider_prem_29 { get; set; }
        public int rider_loading_rate_29 { get; set; }
        public int rider_si_31 { get; set; }
        public decimal rider_prem_31 { get; set; }
        public int rider_loading_rate_31 { get; set; }
        public int rider_si_32 { get; set; }
        public decimal rider_prem_32 { get; set; }
        public int rider_loading_rate_32 { get; set; }
        public int rider_si_33 { get; set; }
        public decimal rider_prem_33 { get; set; }
        public int rider_loading_rate_33 { get; set; }
        public int rider_si_34 { get; set; }
        public decimal rider_prem_34 { get; set; }
        public int rider_loading_rate_34 { get; set; }
        public int rider_si_35 { get; set; }
        public decimal rider_prem_35 { get; set; }
        public int rider_loading_rate_35 { get; set; }
        public int rider_si_36 { get; set; }
        public decimal rider_prem_36 { get; set; }
        public int rider_loading_rate_36 { get; set; }
        public int rider_si_37 { get; set; }
        public decimal rider_prem_37 { get; set; }
        public int rider_loading_rate_37 { get; set; }
        public int rider_si_38 { get; set; }
        public decimal rider_prem_38 { get; set; }
        public int rider_loading_rate_38 { get; set; }
        public int rider_si_39 { get; set; }
        public decimal rider_prem_39 { get; set; }
        public int rider_loading_rate_39 { get; set; }
        public int rider_si_41 { get; set; }
        public decimal rider_prem_41 { get; set; }
        public int rider_loading_rate_41 { get; set; }
        public int rider_si_42 { get; set; }
        public decimal rider_prem_42 { get; set; }
        public int rider_loading_rate_42 { get; set; }
        public int rider_si_43 { get; set; }
        public decimal rider_prem_43 { get; set; }
        public int rider_loading_rate_43 { get; set; }
        public int rider_si_44 { get; set; }
        public decimal rider_prem_44 { get; set; }
        public int rider_loading_rate_44 { get; set; }
        public int rider_si_45 { get; set; }
        public decimal rider_prem_45 { get; set; }
        public int rider_loading_rate_45 { get; set; }
        public int rider_si_46 { get; set; }
        public decimal rider_prem_46 { get; set; }
        public int rider_loading_rate_46 { get; set; }
        public int rider_si_47 { get; set; }
        public decimal rider_prem_47 { get; set; }
        public int rider_loading_rate_47 { get; set; }
        public int rider_si_48 { get; set; }
        public decimal rider_prem_48 { get; set; }
        public int rider_loading_rate_48 { get; set; }
        public int rider_si_49 { get; set; }
        public decimal rider_prem_49 { get; set; }
        public int rider_loading_rate_49 { get; set; }
        public int rider_si_51 { get; set; }
        public decimal rider_prem_51 { get; set; }
        public int rider_loading_rate_51 { get; set; }
        public int rider_si_52 { get; set; }
        public decimal rider_prem_52 { get; set; }
        public int rider_loading_rate_52 { get; set; }
        public int rider_si_53 { get; set; }
        public decimal rider_prem_53 { get; set; }
        public int rider_loading_rate_53 { get; set; }
        public int rider_si_54 { get; set; }
        public decimal rider_prem_54 { get; set; }
        public int rider_loading_rate_54 { get; set; }
        public int rider_si_55 { get; set; }
        public decimal rider_prem_55 { get; set; }
        public int rider_loading_rate_55 { get; set; }
        public int rider_si_56 { get; set; }
        public decimal rider_prem_56 { get; set; }
        public int rider_loading_rate_56 { get; set; }
        public int rider_si_57 { get; set; }
        public decimal rider_prem_57 { get; set; }
        public int rider_loading_rate_57 { get; set; }
        public int rider_si_58 { get; set; }
        public decimal rider_prem_58 { get; set; }
        public int rider_loading_rate_58 { get; set; }
        public int rider_si_59 { get; set; }
        public decimal rider_prem_59 { get; set; }
        public int rider_loading_rate_59 { get; set; }
        public int rider_si_61 { get; set; }
        public decimal rider_prem_61 { get; set; }
        public int rider_loading_rate_61 { get; set; }
        public int rider_si_62 { get; set; }
        public decimal rider_prem_62 { get; set; }
        public int rider_loading_rate_62 { get; set; }
        public int rider_si_63 { get; set; }
        public decimal rider_prem_63 { get; set; }
        public int rider_loading_rate_63 { get; set; }
        public int rider_si_64 { get; set; }
        public decimal rider_prem_64 { get; set; }
        public int rider_loading_rate_64 { get; set; }
        public int rider_si_65 { get; set; }
        public decimal rider_prem_65 { get; set; }
        public int rider_loading_rate_65 { get; set; }
        public int rider_si_66 { get; set; }
        public decimal rider_prem_66 { get; set; }
        public int rider_loading_rate_66 { get; set; }
        public int rider_si_67 { get; set; }
        public decimal rider_prem_67 { get; set; }
        public int rider_loading_rate_67 { get; set; }
        public int rider_si_68 { get; set; }
        public decimal rider_prem_68 { get; set; }
        public int rider_loading_rate_68 { get; set; }
        public int rider_si_69 { get; set; }
        public decimal rider_prem_69 { get; set; }
        public int rider_loading_rate_69 { get; set; }
        public int rider_si_71 { get; set; }
        public decimal rider_prem_71 { get; set; }
        public int rider_loading_rate_71 { get; set; }
        public int rider_si_72 { get; set; }
        public decimal rider_prem_72 { get; set; }
        public int rider_loading_rate_72 { get; set; }
        public int rider_si_73 { get; set; }
        public decimal rider_prem_73 { get; set; }
        public int rider_loading_rate_73 { get; set; }
        public int rider_si_74 { get; set; }
        public decimal rider_prem_74 { get; set; }
        public int rider_loading_rate_74 { get; set; }
        public int rider_si_75 { get; set; }
        public decimal rider_prem_75 { get; set; }
        public int rider_loading_rate_75 { get; set; }
        public int rider_si_76 { get; set; }
        public decimal rider_prem_76 { get; set; }
        public int rider_loading_rate_76 { get; set; }
        public int rider_si_77 { get; set; }
        public decimal rider_prem_77 { get; set; }
        public int rider_loading_rate_77 { get; set; }
        public int rider_si_78 { get; set; }
        public decimal rider_prem_78 { get; set; }
        public int rider_loading_rate_78 { get; set; }
        public int rider_si_79 { get; set; }
        public decimal rider_prem_79 { get; set; }
        public int rider_loading_rate_79 { get; set; }
        public int rider_si_81 { get; set; }
        public decimal rider_prem_81 { get; set; }
        public int rider_loading_rate_81 { get; set; }
        public int rider_si_82 { get; set; }
        public decimal rider_prem_82 { get; set; }
        public int rider_loading_rate_82 { get; set; }
        public int rider_si_83 { get; set; }
        public decimal rider_prem_83 { get; set; }
        public int rider_loading_rate_83 { get; set; }
        public int rider_si_84 { get; set; }
        public decimal rider_prem_84 { get; set; }
        public int rider_loading_rate_84 { get; set; }
        public int rider_si_85 { get; set; }
        public decimal rider_prem_85 { get; set; }
        public int rider_loading_rate_85 { get; set; }
        public int rider_si_86 { get; set; }
        public decimal rider_prem_86 { get; set; }
        public int rider_loading_rate_86 { get; set; }
        public int rider_si_87 { get; set; }
        public decimal rider_prem_87 { get; set; }
        public int rider_loading_rate_87 { get; set; }
        public int rider_si_88 { get; set; }
        public decimal rider_prem_88 { get; set; }
        public int rider_loading_rate_88 { get; set; }
        public int rider_si_89 { get; set; }
        public decimal rider_prem_89 { get; set; }
        public int rider_loading_rate_89 { get; set; }
        public int rider_si_91 { get; set; }
        public decimal rider_prem_91 { get; set; }
        public int rider_loading_rate_91 { get; set; }
        public int rider_si_92 { get; set; }
        public decimal rider_prem_92 { get; set; }
        public int rider_loading_rate_92 { get; set; }
        public int rider_si_93 { get; set; }
        public decimal rider_prem_93 { get; set; }
        public int rider_loading_rate_93 { get; set; }
        public int rider_si_94 { get; set; }
        public decimal rider_prem_94 { get; set; }
        public int rider_loading_rate_94 { get; set; }
        public int rider_si_95 { get; set; }
        public decimal rider_prem_95 { get; set; }
        public int rider_loading_rate_95 { get; set; }
        public int rider_si_96 { get; set; }
        public decimal rider_prem_96 { get; set; }
        public int rider_loading_rate_96 { get; set; }
        public int rider_si_97 { get; set; }
        public decimal rider_prem_97 { get; set; }
        public int rider_loading_rate_97 { get; set; }
        public int rider_si_98 { get; set; }
        public decimal rider_prem_98 { get; set; }
        public int rider_loading_rate_98 { get; set; }
        public int rider_si_99 { get; set; }
        public decimal rider_prem_99 { get; set; }
        public int rider_loading_rate_99 { get; set; }
        public int rider_si_101 { get; set; }
        public decimal rider_prem_101 { get; set; }
        public int rider_loading_rate_101 { get; set; }
        public int rider_si_102 { get; set; }
        public decimal rider_prem_102 { get; set; }
        public int rider_loading_rate_102 { get; set; }
        public int rider_si_103 { get; set; }
        public decimal rider_prem_103 { get; set; }
        public int rider_loading_rate_103 { get; set; }
        public int rider_si_104 { get; set; }
        public decimal rider_prem_104 { get; set; }
        public int rider_loading_rate_104 { get; set; }
        public int rider_si_105 { get; set; }
        public decimal rider_prem_105 { get; set; }
        public int rider_loading_rate_105 { get; set; }
        public int rider_si_106 { get; set; }
        public decimal rider_prem_106 { get; set; }
        public int rider_loading_rate_106 { get; set; }
        public int rider_si_107 { get; set; }
        public decimal rider_prem_107 { get; set; }
        public int rider_loading_rate_107 { get; set; }
        public int rider_si_108 { get; set; }
        public decimal rider_prem_108 { get; set; }
        public int rider_loading_rate_108 { get; set; }
        public int rider_si_109 { get; set; }
        public decimal rider_prem_109 { get; set; }
        public int rider_loading_rate_109 { get; set; }
        public int rider_si_110 { get; set; }
        public decimal rider_prem_110 { get; set; }
        public int rider_loading_rate_110 { get; set; }
        public int rider_si_210 { get; set; }
        public decimal rider_prem_210 { get; set; }
        public int rider_loading_rate_210 { get; set; }
        public int rider_si_310 { get; set; }
        public decimal rider_prem_310 { get; set; }
        public int rider_loading_rate_310 { get; set; }
        public int rider_si_410 { get; set; }
        public decimal rider_prem_410 { get; set; }
        public int rider_loading_rate_410 { get; set; }
        public int rider_si_510 { get; set; }
        public decimal rider_prem_510 { get; set; }
        public int rider_loading_rate_510 { get; set; }
        public int rider_si_610 { get; set; }
        public decimal rider_prem_610 { get; set; }
        public int rider_loading_rate_610 { get; set; }
        public int rider_si_710 { get; set; }
        public decimal rider_prem_710 { get; set; }
        public int rider_loading_rate_710 { get; set; }
        public int rider_si_810 { get; set; }
        public decimal rider_prem_810 { get; set; }
        public int rider_loading_rate_810 { get; set; }
        public int rider_si_910 { get; set; }
        public decimal rider_prem_910 { get; set; }
        public int rider_loading_rate_910 { get; set; }
        public int rider_si_1010 { get; set; }
        public decimal rider_prem_1010 { get; set; }
        public int rider_loading_rate_1010 { get; set; }
        [Key]
        public long policy_no { get; set; }
     
    }
}
