using System.ComponentModel.DataAnnotations;

namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class OptimaSeniorRNE
    {
        public string? jobid { get; set; }
        public string? batchid { get; set; }
        public string? splitid { get; set; }
        public TimeSpan? extractedon { get; set; }
        public short? qcstatus { get; set; }
        public string? qcmsdg { get; set; }
        public TimeSpan? qcon { get; set; }
        public short? ispreintreq { get; set; }
        public short? printstatus { get; set; }
        public string? printmesg { get; set; }
        public TimeSpan? printedon { get; set; }
        public string? partnerflag { get; set; }
        public TimeSpan? noticedate { get; set; }
        public decimal? qc_tot_premium { get; set; }
        public decimal? qc_service_tax { get; set; }
        public string? partnername { get; set; }
        public string? partneruniqueid { get; set; }
        public decimal? partnertotpremium { get; set; }
        public decimal? partner_tax { get; set; }
        public int? prod_code { get; set; }
        public string? prod_name { get; set; }
        public string? split_flag { get; set; }
        public long? reference_num { get; set; }
        public TimeSpan? reference_date { get; set; }
        [Key]
        public string policy_number { get; set; }
        public long? branchcode { get; set; }
        public string? branchname { get; set; }
        public string? customer_id { get; set; }
        public string? customername { get; set; }
        public string? txt_salutation { get; set; }
        public string? location_code { get; set; }
        public string? txt_address_line_1 { get; set; }
        public string? txt_address_line_2 { get; set; }
        public string? txt_apartment { get; set; }
        public string? txt_street { get; set; }
        public string? txt_areavillage { get; set; }
        public string? txt_citydistrict { get; set; }
        public string? txt_state { get; set; }
        public string? state_code { get; set; }
        public string? state_regis { get; set; }
        public string? txt_pincode { get; set; }
        public string? txt_nationality { get; set; }
        public string? txt_mobile { get; set; }
        public string? txt_telephone { get; set; }
        public string? txt_dealer_cd { get; set; }
        public string? imdname { get; set; }
        public string? imdmobile { get; set; }
        public string? vertical_name { get; set; }
        public string? verticalname { get; set; }
        public DateTime? policy_start_date { get; set; }
        public DateTime? policy_expiry_date { get; set; }
        public string? policy_period { get; set; }
        public string? policyplan { get; set; }
        public string? policy_type { get; set; }
        public string? txt_family { get; set; }
        public string? tier_type { get; set; }
        public int? claimcount { get; set; }
        public decimal? num_tot_premium { get; set; }
        public decimal? num_net_premium { get; set; }
        public decimal? num_service_tax { get; set; }
        public string? txt_insuredname1 { get; set; }
        public string? txt_insuredname2 { get; set; }
        public string? txt_insuredname3 { get; set; }
        public string? txt_insuredname4 { get; set; }
        public string? txt_insuredname5 { get; set; }
        public string? txt_insuredname6 { get; set; }
        public string? txt_insured_dob1 { get; set; }
        public string? txt_insured_dob2 { get; set; }
        public string? txt_insured_dob3 { get; set; }
        public string? txt_insured_dob4 { get; set; }
        public string? txt_insured_dob5 { get; set; }
        public string? txt_insured_dob6 { get; set; }
        public string? txt_insured_relation1 { get; set; }
        public string? txt_insured_relation2 { get; set; }
        public string? txt_insured_relation3 { get; set; }
        public string? txt_insured_relation4 { get; set; }
        public string? txt_insured_relation5 { get; set; }
        public string? txt_insured_relation6 { get; set; }
        public string? txt_insured_age1 { get; set; }
        public string? txt_insured_age2 { get; set; }
        public string? txt_insured_age3 { get; set; }
        public string? txt_insured_age4 { get; set; }
        public string? txt_insured_age5 { get; set; }
        public string? txt_insured_age6 { get; set; }
        public string? txt_insured_gender1 { get; set; }
        public string? txt_insured_gender2 { get; set; }
        public string? txt_insured_gender3 { get; set; }
        public string? txt_insured_gender4 { get; set; }
        public string? txt_insured_gender5 { get; set; }
        public string? txt_insured_gender6 { get; set; }
        public string? member_id1 { get; set; }
        public string? member_id2 { get; set; }
        public string? member_id3 { get; set; }
        public string? member_id4 { get; set; }
        public string? member_id5 { get; set; }
        public string? member_id6 { get; set; }
        public string? nominee_name1 { get; set; }
        public string? nominee_name2 { get; set; }

        public string? nominee_name3 { get; set; }
        public string? nominee_name4 { get; set; }
        public string? nominee_name5 { get; set; }
        public string? nominee_name6 { get; set; }
        public string? nominee_relationship1 { get; set; }
        public string? nominee_relationship2 { get; set; }
        public string? nominee_relationship3 { get; set; }
        public string? nominee_relationship4 { get; set; }
        public string? nominee_relationship5 { get; set; }
        public string? nominee_relationship6 { get; set; }
        public string? pre_existing_disease1 { get; set; }
        public string? pre_existing_disease2 { get; set; }
        public string? pre_existing_disease3 { get; set; }
        public string? pre_existing_disease4 { get; set; }
        public string? pre_existing_disease5 { get; set; }
        public string? pre_existing_disease6 { get; set; }
        public decimal? sum_insured1 { get; set; }
        public decimal? sum_insured2 { get; set; }
        public decimal? sum_insured3 { get; set; }
        public decimal? sum_insured4 { get; set; }
        public decimal? sum_insured5 { get; set; }
        public decimal? sum_insured6 { get; set; }
        public string? insured_cb1 { get; set; }
        public string? insured_cb2 { get; set; }
        public string? insured_cb3 { get; set; }
        public string? insured_cb4 { get; set; }
        public string? insured_cb5 { get; set; }
        public string? insured_cb6 { get; set; }
        public decimal? premium_insured1 { get; set; }
        public decimal? premium_insured2 { get; set; }
        public decimal? premium_insured3 { get; set; }
        public decimal? premium_insured4 { get; set; }
        public decimal? premium_insured5 { get; set; }
        public decimal? premium_insured6 { get; set; }
        public decimal? insured_deductable1 { get; set; }
        public decimal? insured_deductable2 { get; set; }
        public decimal? insured_deductable3 { get; set; }
        public decimal? insured_deductable4 { get; set; }
        public decimal? insured_deductable5 { get; set; }
        public decimal? insured_deductable6 { get; set; }
        public decimal? insured_loadingper1 { get; set; }
        public decimal? insured_loadingper2 { get; set; }
        public decimal? insured_loadingper3 { get; set; }
        public decimal? insured_loadingper4 { get; set; }
        public decimal? insured_loadingper5 { get; set; }
        public decimal? insured_loadingper6 { get; set; }
        public decimal? insured_loadingamt1 { get; set; }
        public decimal? insured_loadingamt2 { get; set; }
        public decimal? insured_loadingamt3 { get; set; }
        public decimal? insured_loadingamt4 { get; set; }
        public decimal? insured_loadingamt5 { get; set; }
        public decimal? insured_loadingamt6 { get; set; }
        public decimal? insured_rb_claimamt1 { get; set; }
        public decimal? insured_rb_claimamt2 { get; set; }
        public decimal? insured_rb_claimamt3 { get; set; }
        public decimal? insured_rb_claimamt4 { get; set; }
        public decimal? insured_rb_claimamt5 { get; set; }
        public decimal? insured_rb_claimamt6 { get; set; }
        public decimal? copayper1 { get; set; }
        public decimal? copayper2 { get; set; }
        public decimal? copayper3 { get; set; }
        public decimal? copayper4 { get; set; }
        public decimal? copayper5 { get; set; }
        public decimal? copayper6 { get; set; }
        public decimal? copayamt1 { get; set; }
        public decimal? copayamt2 { get; set; }
        public decimal? copayamt3 { get; set; }
        public decimal? copayamt4 { get; set; }
        public decimal? copayamt5 { get; set; }
        public decimal? copayamt6 { get; set; }
        public decimal? fitness_discount1 { get; set; }
        public decimal? fitness_discount2 { get; set; }
        public decimal? fitness_discount3 { get; set; }
        public decimal? fitness_discount4 { get; set; }
        public decimal? fitness_discount5 { get; set; }
        public decimal? fitness_discount6 { get; set; }
        public decimal? health_incentive1 { get; set; }
        public decimal? health_incentive2 { get; set; }
        public decimal? health_incentive3 { get; set; }
        public decimal? health_incentive4 { get; set; }
        public decimal? health_incentive5 { get; set; }
        public decimal? health_incentive6 { get; set; }
        public decimal? wellness_discount1 { get; set; }
        public decimal? wellness_discount2 { get; set; }
        public decimal? wellness_discount3 { get; set; }
        public decimal? wellness_discount4 { get; set; }
        public decimal? wellness_discount5 { get; set; }
        public decimal? wellness_discount6 { get; set; }
        public decimal? stayactive1 { get; set; }
        public decimal? stayactive2 { get; set; }
        public decimal? stayactive3 { get; set; }
        public decimal? stayactive4 { get; set; }
        public decimal? stayactive5 { get; set; }
        public decimal? stayactive6 { get; set; }
        public string? covername11 { get; set; }
        public decimal? coversi11 { get; set; }
        public decimal? coverprem11 { get; set; }
        public string? covername12 { get; set; }
        public decimal? coversi12 { get; set; }
        public decimal? coverprem12 { get; set; }
        public string? covername13 { get; set; }
        public decimal? coversi13 { get; set; }
        public decimal? coverprem13 { get; set; }
        public string? covername14 { get; set; }
        public decimal? coversi14 { get; set; }
        public decimal? coverprem14 { get; set; }
        public string? covername15 { get; set; }
        public decimal? coversi15 { get; set; }
        public decimal? coverprem15 { get; set; }
        public string? covername16 { get; set; }
        public decimal? coversi16 { get; set; }
        public decimal? coverprem16 { get; set; }
        public string? covername21 { get; set; }
        public decimal? coversi21 { get; set; }
        public decimal? coverprem21 { get; set; }
        public string? covername22 { get; set; }
        public decimal? coversi22 { get; set; }
        public decimal? coverprem22 { get; set; }
        public string? covername23 { get; set; }
        public decimal? coversi23 { get; set; }
        public decimal? coverprem23 { get; set; }
        public string? covername24 { get; set; }
        public decimal? coversi24 { get; set; }
        public decimal? coverprem24 { get; set; }
        public string? covername25 { get; set; }
        public decimal? coversi25 { get; set; }
        public decimal? coverprem25 { get; set; }
        public string? covername26 { get; set; }
        public decimal? coversi26 { get; set; }
        public decimal? coverprem26 { get; set; }
        public string? covername31 { get; set; }
        public decimal? coversi31 { get; set; }
        public decimal? coverprem31 { get; set; }
        public string? covername32 { get; set; }
        public decimal? coversi32 { get; set; }
        public decimal? coverprem32 { get; set; }
        public string? covername33 { get; set; }
        public decimal? coversi33 { get; set; }
        public decimal? coverprem33 { get; set; }
        public string? covername34 { get; set; }
        public decimal? coversi34 { get; set; }
        public decimal? coverprem34 { get; set; }
        public string? covername35 { get; set; }
        public decimal? coversi35 { get; set; }
        public decimal? coverprem35 { get; set; }
        public string? covername36 { get; set; }
        public decimal? coversi36 { get; set; }
        public decimal? coverprem36 { get; set; }
        public string? covername41 { get; set; }
        public decimal? coversi41 { get; set; }
        public decimal? coverprem41 { get; set; }
        public string? covername42 { get; set; }
        public decimal? coversi42 { get; set; }
        public decimal? coverprem42 { get; set; }
        public string? covername43 { get; set; }
        public decimal? coversi43 { get; set; }
        public decimal? coverprem43 { get; set; }
        public string? covername44 { get; set; }
        public decimal? coversi44 { get; set; }
        public decimal? coverprem44 { get; set; }
        public string? covername45 { get; set; }
        public decimal? coversi45 { get; set; }
        public decimal? coverprem45 { get; set; }
        public string? covername46 { get; set; }
        public decimal? coversi46 { get; set; }
        public decimal? coverprem46 { get; set; }
        public string? covername51 { get; set; }
        public decimal? coversi51 { get; set; }
        public decimal? coverprem51 { get; set; }
        public string? covername52 { get; set; }
        public decimal? coversi52 { get; set; }
        public decimal? coverprem52 { get; set; }
        public string? covername53 { get; set; }
        public decimal? coversi53 { get; set; }
        public decimal? coverprem53 { get; set; }
        public string? covername54 { get; set; }
        public decimal? coversi54 { get; set; }

        public decimal? coverprem54 { get; set; }
        public string? covername55 { get; set; }
        public decimal? coversi55 { get; set; }
        public decimal? coverprem55 { get; set; }
        public string? covername56 { get; set; }
        public decimal? coversi56 { get; set; }
        public decimal? coverprem56 { get; set; }
        public string? covername61 { get; set; }
        public decimal? coversi61 { get; set; }
        public decimal? coverprem61 { get; set; }
        public string? covername62 { get; set; }
        public decimal? coversi62 { get; set; }
        public decimal? coverprem62 { get; set; }
        public string? covername63 { get; set; }
        public decimal? coversi63 { get; set; }
        public decimal? coverprem63 { get; set; }
        public string? covername64 { get; set; }
        public decimal? coversi64 { get; set; }
        public decimal? coverprem64 { get; set; }
        public string? covername65 { get; set; }
        public decimal? coversi65 { get; set; }
        public decimal? coverprem65 { get; set; }
        public string? covername66 { get; set; }
        public decimal? coversi66 { get; set; }
        public decimal? coverprem66 { get; set; }
        public string? upselltype1 { get; set; }
        public string? upselltype2 { get; set; }
        public string? upselltype3 { get; set; }
        public string? upselltype4 { get; set; }
        public string? upselltype5 { get; set; }
        public string? upsellvalue1 { get; set; }
        public string? upsellvalue2 { get; set; }
        public string? upsellvalue3 { get; set; }
        public string? upsellvalue4 { get; set; }
        public string? upsellvalue5 { get; set; }
        public decimal? upsellpremium1 { get; set; }
        public decimal? upsellpremium2 { get; set; }
        public decimal? upsellpremium3 { get; set; }
        public decimal? upsellpremium4 { get; set; }
        public decimal? upsellpremium5 { get; set; }
        public decimal? upselltax1 { get; set; }
        public decimal? upselltax2 { get; set; }
        public decimal? upselltax3 { get; set; }
        public decimal? upselltax4 { get; set; }
        public decimal? upselltax5 { get; set; }
        public string? pollddesc1 { get; set; }
        public string? pollddesc2 { get; set; }
        public string? pollddesc3 { get; set; }
        public string? pollddesc4 { get; set; }
        public string? pollddesc5 { get; set; }
        public decimal? polldrate1 { get; set; }
        public decimal? polldrate2 { get; set; }
        public decimal? polldrate3 { get; set; }
        public decimal? polldrate4 { get; set; }
        public decimal? polldrate5 { get; set; }
        public decimal? polldamt1 { get; set; }
        public decimal? polldamt2 { get; set; }
        public decimal? polldamt3 { get; set; }
        public decimal? polldamt4 { get; set; }
        public decimal? polldamt5 { get; set; }
        public string? rpolicy_no { get; set; }
        public string? othersystempolno { get; set; }
        public decimal? reservbenefis1 { get; set; }
        public decimal? reservbenefis2 { get; set; }
        public decimal? reservbenefis3 { get; set; }
        public decimal? reservbenefis4 { get; set; }
        public decimal? reservbenefis5 { get; set; }
        public decimal? reservbenefis6 { get; set; }
        public decimal? coverloadingrate11 { get; set; }
        public decimal? coverloadingrate12 { get; set; }
        public decimal? coverloadingrate13 { get; set; }
        public decimal? coverloadingrate14 { get; set; }
        public decimal? coverloadingrate15 { get; set; }
        public decimal? coverloadingrate16 { get; set; }
        public decimal? coverloadingrate21 { get; set; }
        public decimal? coverloadingrate22 { get; set; }
        public decimal? coverloadingrate23 { get; set; }
        public decimal? coverloadingrate24 { get; set; }
        public decimal? coverloadingrate25 { get; set; }
        public decimal? coverloadingrate26 { get; set; }
        public decimal? coverloadingrate31 { get; set; }
        public decimal? coverloadingrate32 { get; set; }
        public decimal? coverloadingrate33 { get; set; }
        public decimal? coverloadingrate34 { get; set; }
        public decimal? coverloadingrate35 { get; set; }
        public decimal? coverloadingrate36 { get; set; }
        public decimal? coverloadingrate41 { get; set; }
        public decimal? coverloadingrate42 { get; set; }
        public decimal? coverloadingrate43 { get; set; }
        public decimal? coverloadingrate44 { get; set; }
        public decimal? coverloadingrate45 { get; set; }
        public decimal? coverloadingrate46 { get; set; }
        public decimal? coverloadingrate51 { get; set; }
        public decimal? coverloadingrate52 { get; set; }
        public decimal? coverloadingrate53 { get; set; }
        public decimal? coverloadingrate54 { get; set; }
        public decimal? coverloadingrate55 { get; set; }
        public decimal? coverloadingrate56 { get; set; }
        public decimal? coverloadingrate61 { get; set; }
        public decimal? coverloadingrate62 { get; set; }
        public decimal? coverloadingrate63 { get; set; }
        public decimal? coverloadingrate64 { get; set; }
        public decimal? coverloadingrate65 { get; set; }
        public decimal? coverloadingrate66 { get; set; }
        public decimal? coverbaseloadingrate1 { get; set; }
        public decimal? coverbaseloadingrate2 { get; set; }
        public decimal? coverbaseloadingrate3 { get; set; }
        public decimal? coverbaseloadingrate4 { get; set; }
        public decimal? coverbaseloadingrate5 { get; set; }
        public decimal? coverbaseloadingrate6 { get; set; }
        public string? txt_email { get; set; }
        public string? age_change_flag { get; set; }
        public string? tier_change_flag { get; set; }
        public string? loading_change_flag { get; set; }
        public string? txt_remarks { get; set; }
        public short? isvipflag { get; set; }
        public short? isrnflag { get; set; }
        public string? txt_insured_entrydate1 { get; set; }
        public string? txt_insured_entrydate2 { get; set; }
        public string? txt_insured_entrydate3 { get; set; }
        public string? txt_insured_entrydate4 { get; set; }
        public string? txt_insured_entrydate5 { get; set; }
        public string? txt_insured_entrydate6 { get; set; }
        public string? txt_insured_entrydate7 { get; set; }
        public string? txt_insured_entrydate8 { get; set; }
        public string? txt_insured_entrydate9 { get; set; }
        public string? txt_insured_entrydate10 { get; set; }
        public string? txt_insured_entrydate11 { get; set; }
        public string? txt_insured_entrydate12 { get; set; }
        public string? txt_insuredname7 { get; set; }
        public string? txt_insuredname8 { get; set; }
        public string? txt_insuredname9 { get; set; }
        public string? txt_insuredname10 { get; set; }
        public string? txt_insuredname11 { get; set; }
        public string? txt_insuredname12 { get; set; }
        public string? txt_insured_dob7 { get; set; }
        public string? txt_insured_dob8 { get; set; }
        public string? txt_insured_dob9 { get; set; }
        public string? txt_insured_dob10 { get; set; }
        public string? txt_insured_dob11 { get; set; }
        public string? txt_insured_dob12 { get; set; }
        public string? txt_insured_relation7 { get; set; }
        public string? txt_insured_relation8 { get; set; }
        public string? txt_insured_relation9 { get; set; }
        public string? txt_insured_relation10 { get; set; }
        public string? txt_insured_relation11 { get; set; }
        public string? txt_insured_relation12 { get; set; }
        public string? txt_insured_age7 { get; set; }
        public string? txt_insured_age8 { get; set; }
        public string? txt_insured_age9 { get; set; }
        public string? txt_insured_age10 { get; set; }
        public string? txt_insured_age11 { get; set; }
        public string? txt_insured_age12 { get; set; }
        public string? txt_insured_gender7 { get; set; }
        public string? txt_insured_gender8 { get; set; }
        public string? txt_insured_gender9 { get; set; }
        public string? txt_insured_gender10 { get; set; }
        public string? txt_insured_gender11 { get; set; }
        public string? txt_insured_gender12 { get; set; }
        public string? member_id7 { get; set; }
        public string? member_id8 { get; set; }
        public string? member_id9 { get; set; }
        public string? member_id10 { get; set; }
        public string? member_id11 { get; set; }
        public string? member_id12 { get; set; }
        public string? nominee_name7 { get; set; }
        public string? nominee_name8 { get; set; }
        public string? nominee_name9 { get; set; }
        public string? nominee_name10 { get; set; }
        public string? nominee_name11 { get; set; }
        public string? nominee_name12 { get; set; }
        public string? nominee_relationship7 { get; set; }
        public string? nominee_relationship8 { get; set; }
        public string? nominee_relationship9 { get; set; }
        public string? nominee_relationship10 { get; set; }
        public string? nominee_relationship11 { get; set; }
        public string? nominee_relationship12 { get; set; }
        public string? pre_existing_disease7 { get; set; }
        public string? pre_existing_disease8 { get; set; }
        public string? pre_existing_disease9 { get; set; }
        public string? pre_existing_disease10 { get; set; }
        public string? pre_existing_disease11 { get; set; }
        public string? pre_existing_disease12 { get; set; }
        public decimal? sum_insured7 { get; set; }
        public decimal? sum_insured8 { get; set; }
        public decimal? sum_insured9 { get; set; }
        public decimal? sum_insured10 { get; set; }
        public decimal? sum_insured11 { get; set; }
        public decimal? sum_insured12 { get; set; }
        public string? insured_cb7 { get; set; }
        public string? insured_cb8 { get; set; }
        public string? insured_cb9 { get; set; }
        public string? insured_cb10 { get; set; }
        public string? insured_cb11 { get; set; }
        public string? insured_cb12 { get; set; }
        public decimal? premium_insured7 { get; set; }
        public decimal? premium_insured8 { get; set; }
        public decimal? premium_insured9 { get; set; }
        public decimal? premium_insured10 { get; set; }
        public decimal? premium_insured11 { get; set; }
        public decimal? premium_insured12 { get; set; }
        public decimal? insured_deductable7 { get; set; }
        public decimal? insured_deductable8 { get; set; }
        public decimal? insured_deductable9 { get; set; }
        public decimal? insured_deductable10 { get; set; }
        public decimal? insured_deductable11 { get; set; }
        public decimal? insured_deductable12 { get; set; }
        public decimal? insured_loadingper7 { get; set; }
        public decimal? insured_loadingper8 { get; set; }
        public decimal? insured_loadingper9 { get; set; }
        public decimal? insured_loadingper10 { get; set; }
        public decimal? insured_loadingper11 { get; set; }
        public decimal? insured_loadingper12 { get; set; }
        public decimal? insured_loadingamt7 { get; set; }
        public decimal? insured_loadingamt8 { get; set; }
        public decimal? insured_loadingamt9 { get; set; }
        public decimal? insured_loadingamt10 { get; set; }
        public decimal? insured_loadingamt11 { get; set; }
        public decimal? insured_loadingamt12 { get; set; }
        public decimal? insured_rb_claimamt7 { get; set; }
        public decimal? insured_rb_claimamt8 { get; set; }
        public decimal? insured_rb_claimamt9 { get; set; }
        public decimal? insured_rb_claimamt10 { get; set; }
        public decimal? insured_rb_claimamt11 { get; set; }
        public decimal? insured_rb_claimamt12 { get; set; }
        public decimal? copayper7 { get; set; }
        public decimal? copayper8 { get; set; }
        public decimal? copayper9 { get; set; }
        public decimal? copayper10 { get; set; }
        public decimal? copayper11 { get; set; }
        public decimal? copayper12 { get; set; }
        public decimal? copayamt7 { get; set; }
        public decimal? copayamt8 { get; set; }
        public decimal? copayamt9 { get; set; }
        public decimal? copayamt10 { get; set; }
        public decimal? copayamt11 { get; set; }
        public decimal? copayamt12 { get; set; }
        public decimal? fitness_discount7 { get; set; }
        public decimal? fitness_discount8 { get; set; }
        public decimal? fitness_discount9 { get; set; }
        public decimal? fitness_discount10 { get; set; }
        public decimal? fitness_discount11 { get; set; }
        public decimal? fitness_discount12 { get; set; }
        public decimal? health_incentive7 { get; set; }
        public decimal? health_incentive8 { get; set; }
        public decimal? health_incentive9 { get; set; }
        public decimal? health_incentive10 { get; set; }
        public decimal? health_incentive11 { get; set; }
        public decimal? health_incentive12 { get; set; }
        public decimal? wellness_discount7 { get; set; }
        public decimal? wellness_discount8 { get; set; }
        public decimal? wellness_discount9 { get; set; }
        public decimal? wellness_discount10 { get; set; }
        public decimal? wellness_discount11 { get; set; }
        public decimal? wellness_discount12 { get; set; }
        public decimal? stayactive7 { get; set; }
        public decimal? stayactive8 { get; set; }
        public decimal? stayactive9 { get; set; }
        public decimal? stayactive10 { get; set; }
        public decimal? stayactive11 { get; set; }
        public decimal? stayactive12 { get; set; }
        public decimal? reservbenefis7 { get; set; }
        public decimal? reservbenefis8 { get; set; }
        public decimal? reservbenefis9 { get; set; }
        public decimal? reservbenefis10 { get; set; }
        public decimal? reservbenefis11 { get; set; }
        public decimal? reservbenefis12 { get; set; }
        public decimal? coverbaseloadingrate7 { get; set; }
        public decimal? coverbaseloadingrate8 { get; set; }
        public decimal? coverbaseloadingrate9 { get; set; }
        public decimal? coverbaseloadingrate10 { get; set; }
        public decimal? coverbaseloadingrate11 { get; set; }
        public decimal? coverbaseloadingrate12 { get; set; }

        public string? covername17 { get; set; }
        public string? covername18 { get; set; }
        public string? covername19 { get; set; }
        public string? covername110 { get; set; }
        public string? covername27 { get; set; }
        public string? covername28 { get; set; }
        public string? covername29 { get; set; }
        public string? covername210 { get; set; }
        public string? covername37 { get; set; }
        public string? covername38 { get; set; }
        public string? covername39 { get; set; }
        public string? covername310 { get; set; }
        public string? covername47 { get; set; }
        public string? covername48 { get; set; }
        public string? covername49 { get; set; }
        public string? covername410 { get; set; }
        public string? covername57 { get; set; }
        public string? covername58 { get; set; }
        public string? covername59 { get; set; }
        public string? covername510 { get; set; }
        public string? covername67 { get; set; }
        public string? covername68 { get; set; }
        public string? covername69 { get; set; }
        public string? covername610 { get; set; }
        public string? covername71 { get; set; }
        public string? covername72 { get; set; }
        public string? covername73 { get; set; }
        public string? covername74 { get; set; }
        public string? covername75 { get; set; }
        public string? covername76 { get; set; }
        public string? covername77 { get; set; }
        public string? covername78 { get; set; }
        public string? covername79 { get; set; }
        public string? covername710 { get; set; }
        public string? covername81 { get; set; }
        public string? covername82 { get; set; }
        public string? covername83 { get; set; }
        public string? covername84 { get; set; }
        public string? covername85 { get; set; }
        public string? covername86 { get; set; }
        public string? covername87 { get; set; }
        public string? covername88 { get; set; }
        public string? covername89 { get; set; }
        public string? covername810 { get; set; }
        public string? covername91 { get; set; }
        public string? covername92 { get; set; }
        public string? covername93 { get; set; }
        public string? covername94 { get; set; }
        public string? covername95 { get; set; }
        public string? covername96 { get; set; }
        public string? covername97 { get; set; }
        public string? covername98 { get; set; }
        public string? covername99 { get; set; }
        public string? covername910 { get; set; }
        public string? covername101 { get; set; }
        public string? covername102 { get; set; }
        public string? covername103 { get; set; }
        public string? covername104 { get; set; }
        public string? covername105 { get; set; }
        public string? covername106 { get; set; }
        public string? covername107 { get; set; }
        public string? covername108 { get; set; }
        public string? covername109 { get; set; }
        public string? covername1010 { get; set; }
        public decimal? coversi17 { get; set; }
        public decimal? coversi18 { get; set; }
        public decimal? coversi19 { get; set; }
        public decimal? coversi110 { get; set; }
        public decimal? coversi27 { get; set; }
        public decimal? coversi28 { get; set; }
        public decimal? coversi29 { get; set; }
        public decimal? coversi210 { get; set; }
        public decimal? coversi37 { get; set; }
        public decimal? coversi38 { get; set; }
        public decimal? coversi39 { get; set; }
        public decimal? coversi310 { get; set; }
        public decimal? coversi47 { get; set; }
        public decimal? coversi48 { get; set; }
        public decimal? coversi49 { get; set; }
        public decimal? coversi410 { get; set; }
        public decimal? coversi57 { get; set; }
        public decimal? coversi58 { get; set; }
        public decimal? coversi59 { get; set; }
        public decimal? coversi510 { get; set; }
        public decimal? coversi67 { get; set; }
        public decimal? coversi68 { get; set; }
        public decimal? coversi69 { get; set; }
        public decimal? coversi610 { get; set; }
        public decimal? coversi71 { get; set; }
        public decimal? coversi72 { get; set; }
        public decimal? coversi73 { get; set; }
        public decimal? coversi74 { get; set; }
        public decimal? coversi75 { get; set; }
        public decimal? coversi76 { get; set; }
        public decimal? coversi77 { get; set; }
        public decimal? coversi78 { get; set; }
        public decimal? coversi79 { get; set; }
        public decimal? coversi710 { get; set; }
        public decimal? coversi81 { get; set; }
        public decimal? coversi82 { get; set; }
        public decimal? coversi83 { get; set; }
        public decimal? coversi84 { get; set; }
        public decimal? coversi85 { get; set; }
        public decimal? coversi86 { get; set; }
        public decimal? coversi87 { get; set; }
        public decimal? coversi88 { get; set; }
        public decimal? coversi89 { get; set; }
        public decimal? coversi810 { get; set; }
        public decimal? coversi91 { get; set; }
        public decimal? coversi92 { get; set; }
        public decimal? coversi93 { get; set; }
        public decimal? coversi94 { get; set; }
        public decimal? coversi95 { get; set; }
        public decimal? coversi96 { get; set; }
        public decimal? coversi97 { get; set; }
        public decimal? coversi98 { get; set; }
        public decimal? coversi99 { get; set; }
        public decimal? coversi910 { get; set; }
        public decimal? coversi101 { get; set; }
        public decimal? coversi102 { get; set; }
        public decimal? coversi103 { get; set; }
        public decimal? coversi104 { get; set; }
        public decimal? coversi105 { get; set; }
        public decimal? coversi106 { get; set; }
        public decimal? coversi107 { get; set; }
        public decimal? coversi108 { get; set; }
        public decimal? coversi109 { get; set; }
        public decimal? coversi1010 { get; set; }
        public decimal? coverprem17 { get; set; }
        public decimal? coverprem18 { get; set; }
        public decimal? coverprem19 { get; set; }
        public decimal? coverprem110 { get; set; }
        public decimal? coverprem27 { get; set; }
        public decimal? coverprem28 { get; set; }
        public decimal? coverprem29 { get; set; }
        public decimal? coverprem210 { get; set; }
        public decimal? coverprem37 { get; set; }
        public decimal? coverprem38 { get; set; }
        public decimal? coverprem39 { get; set; }
        public decimal? coverprem310 { get; set; }
        public decimal? coverprem47 { get; set; }
        public decimal? coverprem48 { get; set; }
        public decimal? coverprem49 { get; set; }
        public decimal? coverprem410 { get; set; }
        public decimal? coverprem57 { get; set; }
        public decimal? coverprem58 { get; set; }
        public decimal? coverprem59 { get; set; }
        public decimal? coverprem510 { get; set; }
        public decimal? coverprem67 { get; set; }
        public decimal? coverprem68 { get; set; }
        public decimal? coverprem69 { get; set; }
        public decimal? coverprem610 { get; set; }
        public decimal? coverprem71 { get; set; }
        public decimal? coverprem72 { get; set; }
        public decimal? coverprem73 { get; set; }
        public decimal? coverprem74 { get; set; }
        public decimal? coverprem75 { get; set; }
        public decimal? coverprem76 { get; set; }
        public decimal? coverprem77 { get; set; }
        public decimal? coverprem78 { get; set; }
        public decimal? coverprem79 { get; set; }
        public decimal? coverprem710 { get; set; }
        public decimal? coverprem81 { get; set; }
        public decimal? coverprem82 { get; set; }
        public decimal? coverprem83 { get; set; }
        public decimal? coverprem84 { get; set; }
        public decimal? coverprem85 { get; set; }
        public decimal? coverprem86 { get; set; }
        public decimal? coverprem87 { get; set; }
        public decimal? coverprem88 { get; set; }
        public decimal? coverprem89 { get; set; }
        public decimal? coverprem810 { get; set; }
        public decimal? coverprem91 { get; set; }
        public decimal? coverprem92 { get; set; }
        public decimal? coverprem93 { get; set; }
        public decimal? coverprem94 { get; set; }
        public decimal? coverprem95 { get; set; }
        public decimal? coverprem96 { get; set; }
        public decimal? coverprem97 { get; set; }
        public decimal? coverprem98 { get; set; }
        public decimal? coverprem99 { get; set; }
        public decimal? coverprem910 { get; set; }
        public decimal? coverprem101 { get; set; }
        public decimal? coverprem102 { get; set; }
        public decimal? coverprem103 { get; set; }
        public decimal? coverprem104 { get; set; }
        public decimal? coverprem105 { get; set; }
        public decimal? coverprem106 { get; set; }
        public decimal? coverprem107 { get; set; }
        public decimal? coverprem108 { get; set; }
        public decimal? coverprem109 { get; set; }
        public decimal? coverprem1010 { get; set; }
        public decimal? coverloadingrate17 { get; set; }
        public decimal? coverloadingrate18 { get; set; }
        public decimal? coverloadingrate19 { get; set; }
        public decimal? coverloadingrate110 { get; set; }
        public decimal? coverloadingrate27 { get; set; }
        public decimal? coverloadingrate28 { get; set; }
        public decimal? coverloadingrate29 { get; set; }
        public decimal? coverloadingrate210 { get; set; }
        public decimal? coverloadingrate37 { get; set; }
        public decimal? coverloadingrate38 { get; set; }
        public decimal? coverloadingrate39 { get; set; }
        public decimal? coverloadingrate310 { get; set; }
        public decimal? coverloadingrate47 { get; set; }
        public decimal? coverloadingrate48 { get; set; }
        public decimal? coverloadingrate49 { get; set; }
        public decimal? coverloadingrate410 { get; set; }
        public decimal? coverloadingrate57 { get; set; }
        public decimal? coverloadingrate58 { get; set; }
        public decimal? coverloadingrate59 { get; set; }
        public decimal? coverloadingrate510 { get; set; }
        public decimal? coverloadingrate67 { get; set; }
        public decimal? coverloadingrate68 { get; set; }
        public decimal? coverloadingrate69 { get; set; }
        public decimal? coverloadingrate610 { get; set; }
        public decimal? coverloadingrate71 { get; set; }
        public decimal? coverloadingrate72 { get; set; }
        public decimal? coverloadingrate73 { get; set; }
        public decimal? coverloadingrate74 { get; set; }
        public decimal? coverloadingrate75 { get; set; }
        public decimal? coverloadingrate76 { get; set; }
        public decimal? coverloadingrate77 { get; set; }
        public decimal? coverloadingrate78 { get; set; }
        public decimal? coverloadingrate79 { get; set; }
        public decimal? coverloadingrate710 { get; set; }
        public decimal? coverloadingrate81 { get; set; }
        public decimal? coverloadingrate82 { get; set; }
        public decimal? coverloadingrate83 { get; set; }
        public decimal? coverloadingrate84 { get; set; }
        public decimal? coverloadingrate85 { get; set; }
        public decimal? coverloadingrate86 { get; set; }
        public decimal? coverloadingrate87 { get; set; }
        public decimal? coverloadingrate88 { get; set; }
        public decimal? coverloadingrate89 { get; set; }
        public decimal? coverloadingrate810 { get; set; }
        public decimal? coverloadingrate91 { get; set; }
        public decimal? coverloadingrate92 { get; set; }
        public decimal? coverloadingrate93 { get; set; }
        public decimal? coverloadingrate94 { get; set; }
        public decimal? coverloadingrate95 { get; set; }
        public decimal? coverloadingrate96 { get; set; }
        public decimal? coverloadingrate97 { get; set; }
        public decimal? coverloadingrate98 { get; set; }
        public decimal? coverloadingrate99 { get; set; }
        public decimal? coverloadingrate910 { get; set; }
        public decimal? coverloadingrate101 { get; set; }
        public decimal? coverloadingrate102 { get; set; }
        public decimal? coverloadingrate103 { get; set; }
        public decimal? coverloadingrate104 { get; set; }
        public decimal? coverloadingrate105 { get; set; }
        public decimal? coverloadingrate106 { get; set; }
        public decimal? coverloadingrate107 { get; set; }
        public decimal? coverloadingrate108 { get; set; }
        public decimal? coverloadingrate109 { get; set; }
        public decimal? coverloadingrate1010 { get; set; }
        public decimal? secure_benefit1 { get; set; }
        public decimal? secure_benefit2 { get; set; }
        public decimal? secure_benefit3 { get; set; }
        public decimal? secure_benefit4 { get; set; }
        public decimal? secure_benefit5 { get; set; }
        public decimal? secure_benefit6 { get; set; }
        public decimal? secure_benefit7 { get; set; }
        public decimal? secure_benefit8 { get; set; }
        public decimal? secure_benefit9 { get; set; }
        public decimal? secure_benefit10 { get; set; }
        public decimal? secure_benefit11 { get; set; }
        public decimal? secure_benefit12 { get; set; }
        public decimal? plus_benefit1 { get; set; }
        public decimal? plus_benefit2 { get; set; }
        public decimal? plus_benefit3 { get; set; }
        public decimal? plus_benefit4 { get; set; }
        public decimal? plus_benefit5 { get; set; }
        public decimal? plus_benefit6 { get; set; }
        public decimal? plus_benefit7 { get; set; }
        public decimal? plus_benefit8 { get; set; }
        public decimal? plus_benefit9 { get; set; }
        public decimal? plus_benefit10 { get; set; }
        public decimal? plus_benefit11 { get; set; }
        public decimal? plus_benefit12 { get; set; }
        public string? preventive_hc { get; set; }
        public string? exclusion1 { get; set; }
        public string? exclusion2 { get; set; }
        public string? exclusion3 { get; set; }
        public string? exclusion4 { get; set; }
        public string? exclusion5 { get; set; }
        public string? exclusion6 { get; set; }
        public string? exclusion7 { get; set; }
        public string? exclusion8 { get; set; }
        public string? exclusion9 { get; set; }
        public string? exclusion10 { get; set; }
        public string? exclusion11 { get; set; }
        public string? exclusion12 { get; set; }
        public string? txt_master_policy_no { get; set; }
        public string? txt_customer_uin { get; set; }
        public string? txt_pre_policy_claim_flag { get; set; }
        public string? txt_lifecycle_claim_flag { get; set; }
        public int num_tot_additional_child { get; set; }
        public int gc_reporting_code { get; set; }
        public string? revised_product_name { get; set; }
        public decimal? revised_premium_without_gst { get; set; }
        public decimal? revised_premium_with_gst { get; set; }
        public string? txt_credit_linked { get; set; }
        public decimal? protectorloadingamt1 { get; set; }
        public decimal? protectorloadingamt2 { get; set; }
        public decimal? protectorloadingamt3 { get; set; }
        public decimal? protectorloadingamt4 { get; set; }
        public decimal? protectorloadingamt5 { get; set; }
        public decimal? protectorloadingamt6 { get; set; }
        public decimal? protectorloadingamt7 { get; set; }
        public decimal? protectorloadingamt8 { get; set; }
        public decimal? protectorloadingamt9 { get; set; }
        public decimal? protectorloadingamt10 { get; set; }
        public decimal? protectorloadingamt11 { get; set; }
        public decimal? protectorloadingamt12 { get; set; }
        public string? hdli_policy_no { get; set; }
        public string? hdli_cover_suminsured { get; set; }
        public string? hdli_premium { get; set; }
        public string? hdli_ecs_tagging { get; set; }
        public string? hdli_application_id { get; set; }
        public decimal? no_claim_discount { get; set; }
        public decimal? online_discount { get; set; }
        public decimal? family_discount { get; set; }
        public decimal? longterm_discount { get; set; }
        public decimal? family_discount_PRHDC { get; set; }
        public decimal? insured_Premium1 { get; set; }
        public decimal? insured_Premium2 { get; set; }
        public decimal? insured_Premium3 { get; set; }
        public decimal? insured_Premium4 { get; set; }
        public decimal? insured_Premium5 { get; set; }
        public decimal? insured_Premium6 { get; set; }
        public decimal? base_Premium { get; set; }
        public decimal? loading_Premium1 { get; set; }
        public decimal? loading_Premium2 { get; set; }
        public decimal? loading_Premium3 { get; set; }
        public decimal? loading_Premium4 { get; set; }
        public decimal? loading_Premium5 { get; set; }
        public decimal? loading_Premium6 { get; set; }
        public decimal? loading_Premium { get; set; }
        public decimal? optimaSenior_BasePremium_Loading { get; set; }
        public decimal? optimaSenior_NoClaim_Discount { get; set; }
        public decimal? optimaSenior_Family_Discount { get; set; }
        public decimal? optimaSenior_LongTerm_Discount { get; set; }
        public decimal? optimaSeniorFinalBase_Premium { get; set; }
        public decimal? basePremLoading_Insured1 { get; set; }
        public decimal? basePremLoading_Insured2 { get; set; }
        public decimal? basePremLoading_Insured3 { get; set; }
        public decimal? basePremLoading_Insured4 { get; set; }
        public decimal? basePremLoading_Insured5 { get; set; }
        public decimal? basePremLoading_Insured6 { get; set; }
        public decimal? basePrem_Loading { get; set; }
        public decimal? net_premium { get; set; }
        public decimal? final_Premium { get; set; }
        public decimal? gst { get; set; }
        public decimal? cross_Check { get; set; }
        public decimal? optimasenior_total_Premium { get; set; }
        public decimal? optimasenior_netpremium { get; set; }
        public decimal? optimasenior_gst { get; set; }
        public decimal? verified_total_Premium { get; set; }
        public decimal? verified_netpremium { get; set; }
        public decimal? verified_gst { get; set; }
        public int? no_of_members { get; set; }

    }
}
