using System.ComponentModel.DataAnnotations;

namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class rne_calculated_cover_rg
    {
        public string? jobid { get; set; }
        [Key]
        public int? id { get; set; }
        public string? batchid { get; set; }
        public string policy_number { get; set; }
        //public int prod_code { get; set; }
        public int? noofmembers { get; set; }
        public long? referencenum { get; set; }
        public string? splittype { get; set; }
        public string? splitid { get; set; }
        public string? upsellid { get; set; }
        public short? isupsell { get; set; }
        public string? sectionid { get; set; }
        public string? riskid { get; set; }
        public string? coverid { get; set; }
        public string? riskname { get; set; }
        public string? covername { get; set; }
        public decimal? suminsured { get; set; }
        public decimal? premium { get; set; }
        public DateTime? processedon { get; set; }
        public short? isarchived { get; set; }
        public DateTime? archivedon { get; set; }
        public decimal? loadingrate { get; set; }
        public decimal? loadingamount { get; set; }
        public string? exclusion { get; set; }
        public decimal? isapplicable { get; set; }
        public int? coverseq { get; set; }
        public decimal? discoutpr { get; set; }
        public decimal? discountamount { get; set; }
        public string? coverstartdate { get; set; }
        public string? coverendtdate { get; set; }
        public decimal? covertax { get; set; }
        public decimal? totalpremium { get; set; }
        //public string? upselltype { get; set; }
        //public string? upsellvalue { get; set; }
        //public decimal? upsellpremium { get; set; }
        //public decimal? sum_insured1 { get; set; }
        //public decimal? sum_insured2 { get; set; }
        //public decimal? sum_insured3 { get; set; }
        //public decimal? sum_insured4 { get; set; }
        //public decimal? sum_insured5 { get; set; }
        //public decimal? sum_insured6 { get; set; }
        //public decimal? sum_insured7 { get; set; }
        //public decimal? sum_insured8 { get; set; }
        //public decimal? sum_insured9 { get; set; }
        //public decimal? sum_insured10 { get; set; }
        //public decimal? sum_insured11 { get; set; }
        //public decimal? sum_insured12 { get; set; }
        //public decimal? premium_insured1 { get; set; }
        //public decimal? premium_insured2 { get; set; }
        //public decimal? premium_insured3 { get; set; }
        //public decimal? premium_insured4 { get; set; }
        //public decimal? premium_insured5 { get; set; }
        //public decimal? premium_insured6 { get; set; }
        //public decimal? premium_insured7 { get; set; }
        //public decimal? premium_insured8 { get; set; }
        //public decimal? premium_insured9 { get; set; }
        //public decimal? premium_insured10 { get; set; }
        //public decimal? premium_insured11 { get; set; }
        //public decimal? premium_insured12 { get; set; }
        //public decimal? base_upsell_premium1 { get; set; }
        //public decimal? base_upsell_premium2 { get; set; }
        //public decimal? base_upsell_premium3 { get; set; }
        //public decimal? base_upsell_premium4 { get; set; }
        //public decimal? base_upsell_premium5 { get; set; }
        //public decimal? base_upsell_premium6 { get; set; }
        //public decimal? base_upsell_premium7 { get; set; }
        //public decimal? base_upsell_premium8 { get; set; }
        //public decimal? base_upsell_premium9 { get; set; }
        //public decimal? base_upsell_premium10 { get; set; }
        //public decimal? base_upsell_premium11 { get; set; }
        //public decimal? base_upsell_premium12 { get; set; }
        //public decimal? base_premium1 { get; set; }
        //public decimal? base_premium2 { get; set; }
        //public decimal? base_premium3 { get; set; }
        //public decimal? base_premium4 { get; set; }
        //public decimal? base_premium5 { get; set; }
        //public decimal? base_premium6 { get; set; }
        //public decimal? base_premium7 { get; set; }
        //public decimal? base_premium8 { get; set; }
        //public decimal? base_premium9 { get; set; }
        //public decimal? base_premium10 { get; set; }
        //public decimal? base_premium11 { get; set; }
        //public decimal? base_premium12 { get; set; }
        //public decimal? loading_amount_insured1 { get; set; }
        //public decimal? loading_amount_insured2 { get; set; }
        //public decimal? loading_amount_insured3 { get; set; }
        //public decimal? loading_amount_insured4 { get; set; }
        //public decimal? loading_amount_insured5 { get; set; }
        //public decimal? loading_amount_insured6 { get; set; }
        //public decimal? loading_amount_insured7 { get; set; }
        //public decimal? loading_amount_insured8 { get; set; }
        //public decimal? loading_amount_insured9 { get; set; }
        //public decimal? loading_amount_insured10 { get; set; }
        //public decimal? loading_amount_insured11 { get; set; }
        //public decimal? loading_amount_insured12 { get; set; }
        //public decimal? upsellfinalpremium { get; set; }
        //public string? covername11 { get; set; }
        //public string? covername12 { get; set; }
        //public string? covername13 { get; set; }
        //public string? covername14 { get; set; }
        //public string? covername15 { get; set; }
        //public string? covername16 { get; set; }
        //public string? covername17 { get; set; }
        //public string? covername18 { get; set; }
        //public string? covername19 { get; set; }
        //public string? covername21 { get; set; }
        //public string? covername22 { get; set; }
        //public string? covername23 { get; set; }
        //public string? covername24 { get; set; }
        //public string? covername25 { get; set; }
        //public string? covername26 { get; set; }
        //public string? covername27 { get; set; }
        //public string? covername28 { get; set; }
        //public string? covername29 { get; set; }
        //public string? covername31 { get; set; }
        //public string? covername32 { get; set; }
        //public string? covername33 { get; set; }
        //public string? covername34 { get; set; }
        //public string? covername35 { get; set; }
        //public string? covername36 { get; set; }
        //public string? covername37 { get; set; }
        //public string? covername38 { get; set; }
        //public string? covername39 { get; set; }
        //public string? covername41 { get; set; }
        //public string? covername42 { get; set; }
        //public string? covername43 { get; set; }
        //public string? covername44 { get; set; }
        //public string? covername45 { get; set; }
        //public string? covername46 { get; set; }
        //public string? covername47 { get; set; }
        //public string? covername48 { get; set; }
        //public string? covername49 { get; set; }
        //public string? covername51 { get; set; }
        //public string? covername52 { get; set; }
        //public string? covername53 { get; set; }
        //public string? covername54 { get; set; }
        //public string? covername55 { get; set; }
        //public string? covername56 { get; set; }
        //public string? covername57 { get; set; }
        //public string? covername58 { get; set; }
        //public string? covername59 { get; set; }
        //public string? covername61 { get; set; }
        //public string? covername62 { get; set; }
        //public string? covername63 { get; set; }
        //public string? covername64 { get; set; }
        //public string? covername65 { get; set; }
        //public string? covername66 { get; set; }
        //public decimal? coverprem11 { get; set; }
        //public decimal? coverprem12 { get; set; }
        //public decimal? coverprem13 { get; set; }
        //public decimal? coverprem14 { get; set; }
        //public decimal? coverprem15 { get; set; }
        //public decimal? coverprem16 { get; set; }
        //public decimal? coverprem17 { get; set; }
        //public decimal? coverprem18 { get; set; }
        //public decimal? coverprem19 { get; set; }
        //public decimal? coverprem21 { get; set; }
        //public decimal? coverprem22 { get; set; }
        //public decimal? coverprem23 { get; set; }
        //public decimal? coverprem24 { get; set; }
        //public decimal? coverprem25 { get; set; }
        //public decimal? coverprem26 { get; set; }
        //public decimal? coverprem27 { get; set; }
        //public decimal? coverprem28 { get; set; }
        //public decimal? coverprem29 { get; set; }
        //public decimal? coverprem31 { get; set; }
        //public decimal? coverprem32 { get; set; }
        //public decimal? coverprem33 { get; set; }
        //public decimal? coverprem34 { get; set; }
        //public decimal? coverprem35 { get; set; }
        //public decimal? coverprem36 { get; set; }
        //public decimal? coverprem37 { get; set; }
        //public decimal? coverprem38 { get; set; }
        //public decimal? coverprem39 { get; set; }
        //public decimal? coverprem41 { get; set; }
        //public decimal? coverprem42 { get; set; }
        //public decimal? coverprem43 { get; set; }
        //public decimal? coverprem44 { get; set; }
        //public decimal? coverprem45 { get; set; }
        //public decimal? coverprem46 { get; set; }
        //public decimal? coverprem47 { get; set; }
        //public decimal? coverprem48 { get; set; }
        //public decimal? coverprem49 { get; set; }
        //public decimal? coverprem51 { get; set; }
        //public decimal? coverprem52 { get; set; }
        //public decimal? coverprem53 { get; set; }
        //public decimal? coverprem54 { get; set; }
        //public decimal? coverprem55 { get; set; }
        //public decimal? coverprem56 { get; set; }
        //public decimal? coverprem57 { get; set; }
        //public decimal? coverprem58 { get; set; }
        //public decimal? coverprem59 { get; set; }
        //public decimal? coverprem61 { get; set; }
        //public decimal? coverprem62 { get; set; }
        //public decimal? coverprem63 { get; set; }
        //public decimal? coverprem64 { get; set; }
        //public decimal? coverprem65 { get; set; }
        //public decimal? coverprem66 { get; set; }


    }
}
