using System.ComponentModel.DataAnnotations;

namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class rne_motortab
    {
        public string? jobid { get; set; }
        public string? batchid { get; set; }
        public string? splitid { get; set; }
        public DateTime? extractedon { get; set; }
        public short? qcstatus { get; set; }
        public string? qcmesg { get; set; }
        public DateTime? qcon { get; set; }
        public short? ispreintreq { get; set; }
        public short? printstatus { get; set; }
        public string? printmesg { get; set; }
        public DateTime? printedon { get; set; }
        public string? partnerflag { get; set; }
        public DateTime? noticedate { get; set; }
        public decimal? qc_tot_premium { get; set; }
        public decimal? qc_service_tax { get; set; }
        public string? partnername { get; set; }
        public string? partneruniqueid { get; set; }
        public decimal? partner_tot_premium { get; set; }
        public decimal? partner_tax { get; set; }
        public decimal? product_code { get; set; }
        public string? prod_name { get; set; }
        public string? split_flag { get; set; }
        public long? reference_num { get; set; }
        public DateTime? reference_date { get; set; }
        public string? location_code { get; set; }
        public string? txt_location { get; set; }
        public string? txt_dealer_cd { get; set; }
        public string? txt_salutation { get; set; }
        public string? policy_holders_name { get; set; }
        public string? policy_holders_id { get; set; }
        public string? txt_address_line_1 { get; set; }
        public string? txt_address_line_2 { get; set; }
        public string? txt_apartment { get; set; }
        public string? txt_street { get; set; }
        public string? txt_areavillage { get; set; }
        public string? txt_pincode { get; set; }
        public string? txt_nationality { get; set; }
        public string? txt_mobile { get; set; }
        public string? txt_telephone { get; set; }
        public string? txt_email { get; set; }
        [Key]
        public string policy_number { get; set; }
        public string? policy_period { get; set; }
        public string? policy_type { get; set; }
        public DateTime? policy_expiry_date { get; set; }
        public decimal? num_basic_idv { get; set; }
        public decimal? electrical_idv_premium { get; set; }
        public decimal? nonelectrical_idv_premium { get; set; }
        public decimal? cng_idv { get; set; }
        public decimal? trailers_idv { get; set; }
        public decimal? lpg_idv { get; set; }
        public decimal? idv { get; set; }
        public string? engineno { get; set; }
        public string? rto_location { get; set; }
        public string? chassisno { get; set; }
        public string? registration_number { get; set; }
        public string? vehiclemake { get; set; }
        public string? vehiclemodel { get; set; }
        public string? cubiccapacity { get; set; }
        public string? txt_zone { get; set; }
        public string? yearofmanufacture { get; set; }
        public string? financiername { get; set; }
        public decimal? ncb { get; set; }
        public decimal? num_net_od_premium { get; set; }
        public decimal? num_pa_cover { get; set; }
        public decimal? third_party { get; set; }
        public decimal? other_liability { get; set; }
        public decimal? num_net_premium { get; set; }
        public decimal? service_tax { get; set; }
        public decimal? totalpremium_payable { get; set; }
        public string? txt_dealer_cd_name { get; set; }
        public string? dispatch_location { get; set; }
        public string? verticale_name { get; set; }
        public string? second_verticale_name { get; set; }
        public string? vertical_receipient { get; set; }
        public string? bosg_recipient { get; set; }
        public string? bdm_name { get; set; }
        public string? num_renewal_policy { get; set; }
        public string? num_document { get; set; }
        public decimal? age_discount { get; set; }
        public decimal? occupation_discount { get; set; }
        public decimal? ncb_amount { get; set; }
        public decimal? num_basic_od { get; set; }
        public string? txt_other_loding_discount_used { get; set; }
        public DateTime? dat_insert_date { get; set; } = DateTime.UtcNow;
        public string? citydistrict_perm { get; set; }
        public string? intermediary_name { get; set; }
        public string? intermediary_mobile { get; set; }
        public string? city { get; set; }
        public string? state { get; set; }
        public string? phone_mob { get; set; }
        public DateTime? purchasedate_registrationdate { get; set; }
        public DateTime? policy_start_date { get; set; }
        public string? variant { get; set; }
        public string? seating_capacity { get; set; }
        public string? gvw { get; set; }
        public string? od_premium_breakup_is_required { get; set; }
        public string? od_nominee_name { get; set; }
        public string? od_relationship { get; set; }
        public string? od_age { get; set; }
        public string? od_appointee_name { get; set; }
        public string? od_appointee_relationship { get; set; }
        public string? np_nominee_name { get; set; }
        public string? np_relationship { get; set; }
        public string? np_age { get; set; }
        public decimal? zero_dep_premium { get; set; }
        public decimal? zero_dep_service_tax { get; set; }
        public decimal? zero_dep_premium_payable { get; set; }
        public decimal? ea_premium { get; set; }
        public decimal? ea_service_tax { get; set; }
        public decimal? ea_premium_payable { get; set; }
        public string? store_code { get; set; }
        public string? pol_user_id { get; set; }
        public string? claim_description { get; set; }
        public string? claim_status { get; set; }
        public string? total_claim_amount_desc { get; set; }
        public string? total_claim_amount { get; set; }
        public string? without_ncb_premium { get; set; }
        public string? ncb_premium_desc { get; set; }
        public string? zero_dep_desc { get; set; }
        public string? zero_dep_prem_desc { get; set; }
        public string? ea_prem_desc { get; set; }
        public string? body_type { get; set; }
        public string? flag { get; set; }
        public long? prod_category { get; set; }
        public string? txt_inland_flag { get; set; }
        public string? txt_intermediary_flag { get; set; }
        public string? batchprint_filename { get; set; }
        public string? filenet_filename { get; set; }
        public int? s_no { get; set; }
        public string? processed_flag { get; set; }
        public DateTime? sync_date { get; set; }
        public string? batchprint_flag { get; set; }
        public DateTime? dat_updated_date { get; set; }
        public string? loss_of_use_or_dt_prot_rate { get; set; }
        public string? zero_dept_claim_rate { get; set; }
        public string? ncb_protection_rate { get; set; }
        public string? emergency_assistance_rate { get; set; }
        public string? eng_and_gb_protector_rate { get; set; }
        public string? basic_od_rate { get; set; }
        public string? int_batchprint_filename { get; set; }
        public string? int_filenet_filename { get; set; }
        public string? pincode_zone { get; set; }
        public string? cost_of_consumables { get; set; }
        public decimal? cost_of_consumables_si { get; set; }
        public decimal? cost_of_consumables_prm { get; set; }
        public string? employees_of_insured { get; set; }
        public decimal? employees_of_insured_si { get; set; }
        public decimal? employees_of_insured_prem { get; set; }
        public string? lpg_kit_tp { get; set; }
        public decimal? lpg_kit_tp_si { get; set; }
        public decimal? lpg_kit_tp_prem { get; set; }
        public string? ncb_protection { get; set; }
        public decimal? ncb_protection_si { get; set; }
        public decimal? ncb_protection_prem { get; set; }
        public string? paid_driver { get; set; }
        public decimal? paid_driver_si { get; set; }
        public decimal? paid_driver_prem { get; set; }
        public string? built_cng_od { get; set; }
        public decimal? built_cng_si { get; set; }
        public decimal? built_cng_prem { get; set; }
        public string? built_lpg_od { get; set; }
        public decimal? built_lpg_si { get; set; }
        public decimal? built_lpg_prem { get; set; }
        public string? cng_kit_tp { get; set; }
        public decimal? cng_kit_si { get; set; }
        public decimal? cng_kit_prem { get; set; }
        public string? engine_gearbox { get; set; }
        public decimal? engine_gearbox_si { get; set; }
        public decimal? engine_gearbox_prem { get; set; }
        public string? fiber_tank { get; set; }
        public decimal? fiber_tank_si { get; set; }
        public decimal? fiber_tank_prem { get; set; }
        public string? rally { get; set; }
        public decimal? rally_si { get; set; }
        public decimal? rally_prem { get; set; }
        public string? rally_tp { get; set; }
        public decimal? rally_tp_si { get; set; }
        public decimal? rally_tp_prem { get; set; }
        public string? loss_down_protection { get; set; }
        public decimal? loss_down_protection_si { get; set; }
        public decimal? loss_down_protection_prem { get; set; }
        public string? txt_pa_owner { get; set; }
        public decimal? pa_owner_si { get; set; }
        public decimal? pa_owner_prem { get; set; }
        public string? txt_personal_accident { get; set; }
        public decimal? personal_accident_si { get; set; }
        public decimal? personal_accident_prem { get; set; }
        public string? txt_trailers_tp { get; set; }
        public decimal? trailers_tp_si { get; set; }
        public decimal? trailers_tp_prem { get; set; }
        public string? txt_trailer_od { get; set; }
        public decimal? trailers_od_si { get; set; }
        public decimal? trailers_prem { get; set; }
        public string? txt_zero_dep { get; set; }
        public decimal? zero_dep_si { get; set; }
        public string? txt_emergency_ast { get; set; }
        public decimal? txt_ea_si { get; set; }
        public string? txt_basic_od { get; set; }
        public decimal? basic_od_si { get; set; }
        public string? txt_basic_tp { get; set; }
        public decimal? basic_tp_si { get; set; }
        public decimal? electrical_acess_prem { get; set; }
        public decimal? non_electrical_acess_prem { get; set; }
        public string? txt_cngkit_od { get; set; }
        public decimal? cngkit_od_si { get; set; }
        public decimal? cngkit_od_prem { get; set; }
        public string? txt_lpgkit_od { get; set; }
        public decimal? lpgkit_od_si { get; set; }
        public decimal? lpgkit_od_prem { get; set; }
        public string? product_name { get; set; }
        public string? branch_name { get; set; }
        public long? branchcode { get; set; }
        public string? customer_age { get; set; }
        public decimal? voluntary_access_disc { get; set; }
        public decimal? anti_theft_od { get; set; }
        public decimal? automobile_disc { get; set; }
        public decimal? limited_ownpremises_od { get; set; }
        public decimal? handicapped_od { get; set; }
        public decimal? vintagecar_disc_od { get; set; }
        public decimal? driving_tution_od { get; set; }
        public decimal? limited_ownpremises_tp { get; set; }
        public decimal? geographical_od { get; set; }
        public decimal? foreign_embassy { get; set; }
        public decimal? tppd_discount { get; set; }
        public decimal? geographical_tp { get; set; }
        public decimal? breakin_loading { get; set; }
        public decimal? vehicle_age_disc { get; set; }
        public decimal? built_in_cng_kit { get; set; }
        public decimal? built_in_lpg_kit { get; set; }
        public decimal? fpp { get; set; }
        public decimal? hires_vehicle_drivenby_hirer { get; set; }
        public decimal? ll_paiddriver_cleaner { get; set; }
        public decimal? nfpp { get; set; }
        public decimal? negligence_hirer_hirers { get; set; }
        public decimal? sidecar_disc { get; set; }
        public decimal? driving_tution_tp { get; set; }
        public decimal? adverse_claim_od { get; set; }
        public decimal? adverse_claim_tp { get; set; }
        public decimal? inclusion_imt23 { get; set; }
        public decimal? nocompulsary_excess { get; set; }
        public decimal? private_use { get; set; }
        public decimal? theft_conversionby_hirer { get; set; }
        public decimal? high_tonnage_loading { get; set; }
        public decimal? over_turning_loadnig { get; set; }
        public decimal? confined_site_disc { get; set; }
        public decimal? hire_reward_ambulance_load { get; set; }
        public decimal? hire_hearses_ambulance_load { get; set; }
        public decimal? subvention_discount { get; set; }
        public decimal? cngkit_tp { get; set; }
        public decimal? lpgkit_tp { get; set; }
        public decimal? zerodep_vehbase_prem { get; set; }
        public decimal? emerassi_vehbase_prem { get; set; }
        public decimal? lossdown_vehbase_prem { get; set; }
        public decimal? ncb_vehbase_prem { get; set; }
        public decimal? engine_vehbase_prem { get; set; }
        public decimal? cc_vehbase_prem { get; set; }
        public decimal? zerodep_elec_prem { get; set; }
        public decimal? emerassi_elec_prem { get; set; }
        public decimal? lossdown_elec_prem { get; set; }
        public decimal? ncb_elec_prem { get; set; }
        public decimal? engine_elec_prem { get; set; }
        public decimal? cc_elec_prem { get; set; }
        public decimal? zerodep_non_elec_prem { get; set; }
        public decimal? emerassi_non_elec_prem { get; set; }
        public decimal? lossdown_non_elec_prem { get; set; }
        public decimal? ncb_non_elec_prem { get; set; }
        public decimal? engine_non_elec_prem { get; set; }
        public decimal? cc_non_elec_prem { get; set; }
        public decimal? zerodep_lpg_prem { get; set; }
        public decimal? emerassi_lpg_prem { get; set; }
        public decimal? lossdown_lpg_prem { get; set; }
        public decimal? ncb_lpg_prem { get; set; }
        public decimal? engine_lpg_prem { get; set; }
        public decimal? cc_lpg_prem { get; set; }
        public decimal? zerodep_cng_prem { get; set; }
        public decimal? emerassi_cng_prem { get; set; }
        public decimal? lossdown_cng_prem { get; set; }
        public decimal? ncb_cng_prem { get; set; }
        public decimal? engine_cng_prem { get; set; }
        public decimal? cc_cng_prem { get; set; }
        public decimal? cng_lpg_od_prem { get; set; }
        public decimal? loss_downtime_service_tax { get; set; }
        public decimal? loss_downtime_prem_payable { get; set; }
        public decimal? ncb_protection_st { get; set; }
        public decimal? ncb_protection_prem_payable { get; set; }
        public decimal? engine_gearbox_st { get; set; }
        public decimal? engine_gearbox_prem_payable { get; set; }
        public decimal? cost_consumable_st { get; set; }
        public decimal? cost_consumable_prem_payable { get; set; }
        public string? plan_name { get; set; }
        public string? addon_plan { get; set; }
        public string? addon_desc { get; set; }
        public string? ea_desc { get; set; }
        public string? additional_addon_plan { get; set; }
        public string? addon_premium { get; set; }
        public decimal? age_disc_amt { get; set; }
        public decimal? occupation_disc_amt { get; set; }
        public decimal? emergency_assi_wider_prem { get; set; }
        public string? emergency_assi_wider_st { get; set; }
        public string? emergency_assi_wider_payable { get; set; }
        public string? emi_protector_rate { get; set; }
        public string? higher_protection_rate { get; set; }
        public decimal? higer_removal_cost_prem { get; set; }
        public decimal? higer_removal_cost_prem_st { get; set; }
        public decimal? higer_removal_prem_payable { get; set; }
        public decimal? emi_protector_prem { get; set; }
        public decimal? emi_protector_prem_st { get; set; }
        public decimal? emi_protector_prem_payable { get; set; }
        public decimal? higer_removal_idv { get; set; }
        public decimal? emi_protector_idv { get; set; }
        public string? qr_code { get; set; }
        public string? txt_source_type { get; set; }
        public string? previous_vendor_policy_no { get; set; }
        public string? state_code { get; set; }
        public string? state_regis_num { get; set; }
        public decimal? return_to_invoice_prem { get; set; }
        public decimal? return_to_invoice_st { get; set; }
        public decimal? return_to_invoice_prem_payable { get; set; }
        public string? plan_type { get; set; }
        public string? upsell_desc { get; set; }
        public string? iprocessed_flag { get; set; }
        public DateTime? isync_date { get; set; }
        public string? ibatchprint_flag { get; set; }
        public string? ibatchprint_filename { get; set; }
        public string? vehicle_sub_class { get; set; }
        public string? calculated_chasis_idv { get; set; }
        public string? calculated_body_idv { get; set; }
        public string? addon_not_offered { get; set; }
        public DateTime? dat_tp_start_date { get; set; }
        public DateTime? dat_tp_end_date { get; set; }
        public string? breakin_flag { get; set; }
        public long? gc_reporting_code { get; set; }
        public decimal? num_basic_tp { get; set; }
        public decimal? claim_count { get; set; }
        public string? prev_ncb_protection_flag { get; set; }
        public decimal? tyre_secure_prem { get; set; }
        public decimal? tyre_secure_si { get; set; }
        public decimal? tyre_secure_prem_payable { get; set; }
        public decimal? tyre_secure_st { get; set; }
        public string? name_transfer_flag { get; set; }
        public decimal? totalpremium_withoutncb { get; set; }
        public decimal? totalodpremium_withoutaddon { get; set; }
        public string? claimbenifitpaydflag { get; set; }
        public decimal? bca_premium { get; set; }
        public decimal? bca_service_tax { get; set; }
        public decimal? bca_premium_payable { get; set; }
        public decimal? electric_motor_premium { get; set; }
        public decimal? electric_motor_service_tax { get; set; }
        public decimal? electric_motor_premium_payable { get; set; }
        public decimal? zpc_battery_premium { get; set; }
        public decimal? zpc_battery_service_tax { get; set; }
        public decimal? zpc_battery_premium_payable { get; set; }
        public decimal? loading_rate { get; set; }
        public decimal? discount_rate { get; set; }
        public string? rti_plan_type { get; set; }
        public string? emi_protector_plan_type { get; set; }
        public DateTime? endorsement_eff_date { get; set; }
        public DateTime? claim_date { get; set; }
    }
}
