namespace RenewalGovernancePremiumValidation.Models.Domain
{
    public class tab_health_renewalnotice
    {
            public long? reference_num { get; set; }
            public DateTime? reference_date { get; set; }
            public string? cust_id { get; set; }
            public string? location_code { get; set; }
            public string? policy_holders_name { get; set; }
            public string? txt_apartment { get; set; }
            public string? txt_street { get; set; }
            public string? txt_areavillage { get; set; }
            public string? txt_citydistrict { get; set; }
            public string? txt_state { get; set; }
            public string? txt_pincode { get; set; }
            public string? txt_mobile { get; set; }
            public string? txt_telephone { get; set; }
            public string? txt_off_extn { get; set; }
            public string? prod_name { get; set; }
            public string? policy_number { get; set; }
            public DateTime? policy_expiry_date { get; set; }
            public decimal? total_premium { get; set; }
            public string? txt_policyinsured { get; set; }
            public decimal? total_si { get; set; }
            public DateTime? dat_renewal_notice { get; set; }
            public string? txt_insuredname1 { get; set; }
            public string? txt_insured_dob1 { get; set; }
            public string? txt_insured_age1 { get; set; }
            public string? txt_insured_relation1 { get; set; }
            public string? txt_insured_cb1 { get; set; }
            public string? txt_insuredname2 { get; set; }
            public string? txt_insured_dob2 { get; set; }
            public string? txt_insured_age2 { get; set; }
            public string? txt_insured_relation2 { get; set; }
            public string? txt_insured_cb2 { get; set; }
            public string? txt_insuredname3 { get; set; }
            public string? txt_insured_dob3 { get; set; }
            public string? txt_insured_age3 { get; set; }
            public string? txt_insured_relation3 { get; set; }
            public string? txt_insured_cb3 { get; set; }
            public string? txt_insuredname4 { get; set; }
            public string? txt_insured_dob4 { get; set; }
            public string? txt_insured_age4 { get; set; }
            public string? txt_insured_relation4 { get; set; }
            public string? txt_insured_cb4 { get; set; }
            public string? txt_insuredname5 { get; set; }
            public string? txt_insured_dob5 { get; set; }
            public string? txt_insured_age5 { get; set; }
            public string? txt_insured_relation5 { get; set; }
            public string? txt_insured_cb5 { get; set; }
            public string? txt_insuredname6 { get; set; }
            public string? txt_insured_dob6 { get; set; }
            public string? txt_insured_age6 { get; set; }
            public string? txt_insured_relation6 { get; set; }
            public string? txt_insured_cb6 { get; set; }
            public string? txt_insured_gender1 { get; set; }
            public string? txt_insured_gender2 { get; set; }
            public string? txt_insured_gender3 { get; set; }
            public string? txt_insured_gender4 { get; set; }
            public string? txt_insured_gender5 { get; set; }
            public string? txt_insured_gender6 { get; set; }
            public string? member_id1 { get; set; }
            public string? member_id2 { get; set; }
            public string? member_id3 { get; set; }
            public string? member_id4 { get; set; }
            public string? member_id5 { get; set; }
            public string? member_id6 { get; set; }
            public string? pre_existing_disease1 { get; set; }
            public string? pre_existing_disease2 { get; set; }
            public string? pre_existing_disease3 { get; set; }
            public string? pre_existing_disease4 { get; set; }
            public string? pre_existing_disease5 { get; set; }
            public string? pre_existing_disease6 { get; set; }
            public string? nominee_name1 { get; set; }
            public string? nominee_name2 { get; set; }
            public string? nominee_name3 { get; set; }
            public string? nominee_name4 { get; set; }
            public string? nominee_name5 { get; set; }
            public string? nominee_name6 { get; set; }
            public string? nominee_relationship1 { get; set; }
            public string? nominee_relationship2 { get; set; }
            public string? nominee_relationship3 { get; set; }
            public string? nominee_relationship4 { get; set; }
            public string? nominee_relationship5 { get; set; }
            public string? nominee_relationship6 { get; set; }
            public string? txt_dealer_cd { get; set; }
            public string? verticale_name { get; set; }
            public string? batch_id { get; set; }
            public decimal? num_net_premium { get; set; }
            public decimal? num_service_tax { get; set; }
            public DateTime? dat_insert_date { get; set; }
            public decimal? two_year_premium { get; set; }
            public string? flag { get; set; }
            public long? prod_category { get; set; }
            public string? txt_inland_flag { get; set; }
            public string? txt_intermediary_flag { get; set; }
            public string? batchprint_filename { get; set; }
            public string? filenet_filename { get; set; }
            public int? s_no { get; set; }
            public string? processed_flag { get; set; }
            public DateTime? sync_date { get; set; }
            public string? batchprint_flag { get; set; }
            public DateTime? dat_updated_date { get; set; }
            public string? pincode_zone { get; set; }
            public string? txt_location { get; set; }
            public string? bosg_recipient { get; set; }
            public string? dispatch_location { get; set; }
            public string? vertical_recepient { get; set; }
            public string? int_batchprint_filename { get; set; }
            public string? int_filenet_filename { get; set; }
            public string? branch_name { get; set; }
            public decimal? product_code { get; set; }
            public string? product_name { get; set; }
            public decimal? sum_insured_1 { get; set; }
            public decimal? sum_insured_2 { get; set; }
            public decimal? sum_insured_3 { get; set; }
            public decimal? sum_insured_4 { get; set; }
            public decimal? sum_insured_5 { get; set; }
            public decimal? sum_insured_6 { get; set; }
            public decimal? next_si_1 { get; set; }
            public decimal? next_si_2 { get; set; }
            public decimal? next_si_3 { get; set; }
            public decimal? next_si_4 { get; set; }
            public decimal? next_si_5 { get; set; }
            public decimal? next_si_6 { get; set; }
            public decimal? next_si_prm_11 { get; set; }
            public decimal? next_si_prm_12 { get; set; }
            public decimal? next_si_prm_21 { get; set; }
            public decimal? next_si_prm_22 { get; set; }
            public decimal? next_si_prm_31 { get; set; }
            public decimal? next_si_prm_32 { get; set; }
            public decimal? next_si_prm_41 { get; set; }
            public decimal? next_si_prm_42 { get; set; }
            public decimal? next_si_prm_51 { get; set; }
            public decimal? next_si_prm_52 { get; set; }
            public decimal? next_si_prm_61 { get; set; }
            public decimal? next_si_prm_62 { get; set; }
            public decimal? total_next_si { get; set; }
            public decimal? total_next_si_prm_1year { get; set; }
            public decimal? total_next_si_prm_2year { get; set; }
            public decimal? basic_premium_insured1 { get; set; }
            public decimal? basic_premium_insured2 { get; set; }
            public decimal? basic_premium_insured3 { get; set; }
            public decimal? basic_premium_insured4 { get; set; }
            public decimal? basic_premium_insured5 { get; set; }
            public decimal? basic_premium_insured6 { get; set; }
            public decimal? net_premium_insured1 { get; set; }
            public decimal? net_premium_insured2 { get; set; }
            public decimal? net_premium_insured3 { get; set; }
            public decimal? net_premium_insured4 { get; set; }
            public decimal? net_premium_insured5 { get; set; }
            public decimal? net_premium_insured6 { get; set; }
            public decimal? family_discount { get; set; }
            public decimal? other_loading { get; set; }
            public decimal? other_discount { get; set; }
            public string? insured_risk_cover { get; set; }
            public string? txt_lms_id { get; set; }
            public DateTime policy_start_date { get; set; }
            public DateTime policy_end_date { get; set; }
            public decimal? insured_deductable1 { get; set; }
            public decimal? insured_deductable2 { get; set; }
            public decimal? insured_deductable3 { get; set; }
            public decimal? insured_deductable4 { get; set; }
            public decimal? insured_deductable5 { get; set; }
            public decimal? insured_deductable6 { get; set; }
            public decimal? two_year_net_prem { get; set; }
            public string? txt_family { get; set; }
            public string? auto_pay { get; set; }
            public string? flag_upsell_applicable { get; set; }
            public decimal? num_upsell_si { get; set; }
            public decimal? num_upsell_premium { get; set; }
            public string? qr_code { get; set; }
            public string? state_code { get; set; }
            public string? state_regis_num { get; set; }
            public string? policy_period { get; set; }
            public string? policy_type { get; set; }
            public string? tier_type { get; set; }
            public decimal? three_year_premium { get; set; }
            public string? change_in_age_slab { get; set; }
            public string? mobile_new { get; set; }
            public string? telephone_new { get; set; }
        }
    }
